/** Clean curated engineering college research (12). */
export const engineering = {
  'indian-institute-of-science-bangalore': {
    overview:
      "India's premier research institution. Its engineering division offers a B.Tech in Mathematics & Computing, the 4-year BS (Research) and highly ranked M.Tech/PhD programmes.",
    established: '1909 (founded by Jamsetji Tata)',
    type: 'Deemed public research university; Institute of Eminence',
    affiliation: '',
    approval: 'NAAC A++',
    ranking: 'NIRF 2025: #1 Research, #2 Overall',
    website: 'iisc.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '440 acres',
    highlights: [
      { label: 'Established', value: '1909' },
      { label: 'NIRF 2025', value: '#1 Research, #2 Overall' },
      { label: 'Campus', value: '440 acres' },
      { label: 'Faculty:student', value: '~1:6; ~89% PG/PhD' },
    ],
    courses: [
      {
        name: 'B.Tech Mathematics & Computing',
        duration: '4 yrs',
        seats: '~50',
        eligibility: '10+2 PCM 75% + JEE Advanced (JoSAA)',
        fees: '~Rs 8.38 L total',
      },
      {
        name: 'BS (Research)',
        duration: '4 yrs',
        seats: '~120',
        eligibility: '10+2 PCM 75% + JEE Adv / IAT / NEET',
        fees: '~Rs 0.78 - 3.58 L total',
      },
      {
        name: 'M.Tech (25+ specialisations: AI, CSA, EE, CDS...)',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'BE/B.Tech + GATE',
        fees: '~Rs 56,600 total (+ stipend)',
      },
      {
        name: 'M.Des (Product Design)',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'Graduation + CEED/GATE',
        fees: '~Rs 56,600',
      },
      {
        name: 'PhD',
        duration: '4-6 yrs',
        seats: '-',
        eligibility: "Master's / B.Tech + GATE/NET/interview",
        fees: '~Rs 92,400; JRF ~Rs 37,000/month',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'JEE Advanced - B.Tech MnC (General)', value: 'Closing rank ~856' },
      { label: 'JEE Advanced - BS (Research) (General)', value: 'Closing rank ~2,263' },
      { label: 'GATE - M.Tech CSA', value: '~800 score' },
      { label: 'GATE - M.Tech AI', value: '~780-800' },
      { label: 'GATE - M.Tech EE', value: '~760-790' },
    ],
    admissionSteps: [
      'B.Tech MnC: JEE Advanced -> JoSAA counselling.',
      'BS (Research): JEE Adv / IAT / NEET channels; applications ~May-June.',
      'M.Tech: GATE + test/interview (Feb-Mar applications).',
      'PhD: GATE/NET/JEST etc. + interview.',
    ],
    placements: [
      '2024: highest ~Rs 86 LPA; average/median ~Rs 28 LPA.',
      'Recruiters: Amazon, Microsoft, Google, Nokia, Samsung, Cisco, Siemens, Qualcomm.',
      'Many graduates go to research, academia and PhDs abroad.',
    ],
    campusLife: [
      'Tree-lined 440-acre campus in central Bengaluru; JRD Tata Memorial Library',
      'Fests: Pravega (science, tech & cultural), Rhapsody',
      'Hostels with minimal charges; cricket, football, basketball, gym',
    ],
  },

  'national-institute-of-technology-karnataka-surathkal': {
    overview:
      'One of the top NITs, famous for its beach-side campus on NH-66 and strong CSE/IT placements.',
    established: '1960 (as KREC; NIT in 2002)',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: '',
    ranking: 'NIRF 2025: #17 Engineering; #54 Overall',
    website: 'nitk.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '~296 acres on the Arabian Sea coast, with its own beach',
    highlights: [
      { label: 'Established', value: '1960' },
      { label: 'NIRF 2025', value: '#17 Engineering' },
      { label: 'Campus', value: '~296 acres, beach-side' },
      { label: 'Avg package', value: '~Rs 17.48 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE, AI, IT, CDS, ECE, EEE, Mech, Chem, Metallurgy, Civil, Mining)',
        duration: '4 yrs',
        seats: '~1,000+',
        eligibility: '10+2 PCM 75% + JEE Main (JoSAA/CSAB)',
        fees: '~Rs 6.0 L total (~Rs 1.5-1.7 L/yr)',
      },
      {
        name: 'M.Tech',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'B.Tech 60% + GATE (CCMT)',
        fees: '~Rs 2.5 L total',
      },
      {
        name: 'MBA',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'Graduation 50% + CAT/MAT/CMAT',
        fees: '~Rs 5.13 L total',
      },
      {
        name: 'M.Sc / MCA / PhD',
        duration: '2-3 yrs',
        seats: '-',
        eligibility: 'IIT JAM / NIMCET',
        fees: 'M.Sc ~Rs 1.42 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'JoSAA 2025 (Home State, General) - CSE', value: 'R1 2,726 | Final 2,800' },
      { label: 'AI', value: '3,438 -> 3,579' },
      { label: 'IT', value: '4,086' },
      { label: 'ECE', value: '5,327 -> 5,573' },
      { label: 'EEE', value: '6,674 -> 7,493' },
      { label: 'Mechanical', value: '11,166 -> 12,126' },
      { label: 'Chemical', value: '15,821 -> 18,581' },
      { label: 'Civil', value: '22,534 -> 28,252' },
      { label: 'GATE 2025 M.Tech CSE', value: '735 (R1) -> 693' },
    ],
    admissionSteps: [
      'JEE Main -> JoSAA (50% Home-State Karnataka / 50% Other-State) -> CSAB special rounds.',
      'DASA for foreign/NRI. M.Tech via CCMT; M.Sc via CCMN; MBA via CAT + GD/PI.',
    ],
    placements: [
      '2025: 673 of 835 eligible placed (80.6%); highest ~Rs 63.3 LPA; average ~Rs 17.48 LPA; median ~Rs 14 LPA.',
      'Recruiters: Microsoft, Oracle, Amazon, Wipro, Adobe.',
    ],
    campusLife: [
      "11 boys' + 5 girls' hostels; 1st-yr hostel ~Rs 88,140",
      'Private beach, lighthouse, sports complex with pool, health centre',
      'Fests: Incident (cultural), Engineer (technical)',
    ],
  },

  'rv-college-of-engineering': {
    overview:
      "Karnataka's most sought-after private engineering college, run by the RSST. Top KCET/COMEDK choice for CSE and allied branches.",
    established: '1963',
    type: 'Private-aided autonomous (Rashtreeya Sikshana Samithi Trust); affiliated to VTU',
    affiliation: 'VTU',
    approval: 'AICTE; NAAC A+ (3.3); NBA',
    ranking: 'NIRF 2025: 101-150 band (Engineering)',
    website: 'rvce.edu.in',
    contact: '',
    teachingHospital: '',
    campusSize: '~16.85 acres',
    highlights: [
      { label: 'Established', value: '1963' },
      { label: 'BE seats', value: '~1,400 (CSE 225)' },
      { label: 'Campus', value: '~16.85 acres' },
      { label: 'Avg package', value: '~Rs 24.5 LPA' },
    ],
    courses: [
      {
        name: 'BE (CSE, ISE, AI-ML, Data Science, Cyber Security, ECE, EEE, EIE, Telecom, Mech, Aerospace, Chemical, Civil, Biotech, IEM)',
        duration: '4 yrs',
        seats: '~1,400 (CSE 225)',
        eligibility: '10+2 PCM 45% + KCET / COMEDK / management',
        fees: 'KCET: ~Rs 1 L/yr; COMEDK ~Rs 3.3 L/yr (total ~Rs 13.3 L); Management up to ~Rs 30+ L/yr',
      },
      {
        name: 'M.Tech',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'BE 50% + GATE/PGCET',
        fees: '~Rs 1.6 - 19.3 L',
      },
      {
        name: 'MCA',
        duration: '2 yrs',
        seats: '-',
        eligibility: "Bachelor's with Maths + KMAT/PGCET",
        fees: '~Rs 11.3 L',
      },
    ],
    courseNotes: ['Seat matrix: ~45% KCET, ~30% COMEDK, ~25% management.'],
    cutoffs: [
      { label: 'KCET 2025 (General) - CSE', value: 'R1 234 | Final 499' },
      { label: 'Data Science', value: '367 -> 944' },
      { label: 'AI-ML', value: '429 -> 742' },
      { label: 'Cyber Security', value: '508 -> 990' },
      { label: 'ECE', value: '573 -> 1,100' },
      { label: 'Mechanical', value: '2,901 -> 5,812' },
      { label: 'Civil', value: '9,539 -> 10,832' },
    ],
    admissionSteps: [
      'KCET rank -> KEA counselling; COMEDK UGET rank -> COMEDK counselling; management seats direct.',
      'M.Tech via PGCET/GATE; MCA via PGCET/KMAT.',
    ],
    placements: [
      '2025: 1,009 offers from 262 recruiters; highest ~Rs 67 LPA; average ~Rs 24.5 LPA (as reported).',
      'Recruiters: TCS, Cisco, Genpact, EY, Deloitte, Infosys, VISA.',
    ],
    campusLife: [
      '6 hostels; boys ~Rs 25-45K/yr, girls ~Rs 78K/yr (room)',
      '2,560 desktops, central + 12 dept libraries',
      'Clubs: Astra, Antariksh, Coding Club, Rotaract, NSS; fest: 8th Mile',
    ],
  },

  'institute-of-chemical-technology-mumbai': {
    overview:
      "India's leading institute for chemical engineering and chemical technology, also top-ranked in pharmacy.",
    established: '1933 (as UDCT, University of Bombay)',
    type: 'Deemed-to-be University (state-funded); Category-I autonomy / Elite status',
    affiliation: '',
    approval: 'NAAC A++',
    ranking: 'NIRF 2025: #6 Pharmacy; #41 Engineering; #40 University',
    website: 'ictmumbai.edu.in',
    contact: '',
    teachingHospital: '',
    campusSize: '16 acres (Matunga) + Jalna & Bhubaneswar off-campuses',
    highlights: [
      { label: 'Established', value: '1933' },
      { label: 'NIRF Pharmacy', value: '#6' },
      { label: 'Campus', value: '16 acres Matunga' },
      { label: 'UG median', value: '~Rs 9 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech Chemical Engineering',
        duration: '4 yrs',
        seats: '~75',
        eligibility: '10+2 PCM 50% + MHT-CET (70%) / JEE Main (30% AI)',
        fees: '~Rs 66,300/yr (aided, Maharashtra); total ~Rs 2.65 L',
      },
      {
        name: 'B.Tech (Pharma Chem & Tech, Dyestuff, Surface Coating, Oleo-chem, Fibres & Textile, Food Engg, Polymer Engg)',
        duration: '4 yrs',
        seats: '~30-40 each',
        eligibility: 'Same',
        fees: 'Same band',
      },
      {
        name: 'B.Pharm',
        duration: '4 yrs',
        seats: '-',
        eligibility: '10+2 PCB/PCM 50% + MHT-CET',
        fees: '~Rs 66,300/yr',
      },
      {
        name: 'Integrated M.Tech / M.Tech / M.Pharm',
        duration: '5 / 2 yrs',
        seats: '-',
        eligibility: 'JEE/MHT-CET; GATE/GPAT',
        fees: 'Int. ~Rs 5.28 L; M.Tech ~Rs 1.2-2.0 L',
      },
    ],
    courseNotes: [
      'Non-Maharashtra (all-India) candidates may pay higher fees than aided state-quota rates.',
    ],
    cutoffs: [
      { label: 'MHT-CET (General) - B.Pharm (previous yr)', value: '~99.84 percentile' },
      {
        label: 'Chemical Engg - MHT-CET / JEE Main',
        value: 'Typically 99+ percentile (state) / ~97-98 percentile (AI)',
      },
    ],
    admissionSteps: [
      '70% seats: MHT-CET via Maharashtra CET Cell CAP.',
      "30% seats: JEE Main via ICT's all-India merit.",
      'M.Tech: GATE; M.Pharm: GPAT.',
    ],
    placements: [
      '2025: highest ~Rs 60 LPA; UG median ~Rs 9 LPA; PG median ~Rs 7 LPA; 85-95% placed.',
      'Recruiters: Reliance, Indian Oil, Asian Paints, BASF, Sun Pharma, Lupin, Cipla, HUL.',
    ],
    campusLife: [
      '~1,800 residents across 8 hostels; ~Rs 20,000-39,000/yr',
      'Fests: Vortex (chemistry/tech), Manzar (cultural); TEDx, E-Cell, Tinkering Lab',
    ],
  },

  'veermata-jijabai-technological-institute-mumbai': {
    overview:
      "One of Asia's oldest engineering institutes. Top choice for Maharashtra MHT-CET toppers, with excellent CS placements at very low fees.",
    established: '1887 (as Victoria Jubilee Technical Institute)',
    type: 'Government-aided autonomous (Maharashtra); affiliated to University of Mumbai',
    affiliation: 'University of Mumbai',
    approval: 'NAAC A; multiple NBA programmes',
    ranking: 'NIRF 2025: 101-150 band (Engineering)',
    website: 'vjti.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '~16 acres in Matunga',
    highlights: [
      { label: 'Established', value: '1887' },
      { label: 'B.Tech seats', value: '~540' },
      { label: 'Campus', value: '~16 acres' },
      { label: 'Highest package', value: '~Rs 72.3 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (Computer, IT, CS-Data Science, Electronics, EXTC, Electrical, Mechanical, Civil, Production, Textile)',
        duration: '4 yrs',
        seats: '~540',
        eligibility: '10+2 PCM 45% (40% reserved) + MHT-CET / JEE Main',
        fees: '~Rs 6.71 L total (non-aided rates; EBC/TFWS waivers)',
      },
      {
        name: 'M.Tech (19 specialisations)',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'BE + GATE/PGCET',
        fees: '~Rs 5.46 L',
      },
      {
        name: 'MCA',
        duration: '2 yrs',
        seats: '-',
        eligibility: "Bachelor's + MAH-MCA CET",
        fees: '~Rs 5.16 L',
      },
      {
        name: 'Diploma (6 branches)',
        duration: '3 yrs',
        seats: '-',
        eligibility: 'Class 10',
        fees: '~Rs 1.06 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'MHT-CET (General) - Computer Engg', value: '99.9+ percentile' },
      { label: 'MHT-CET - IT / EXTC', value: '~99.5 - 99.8 percentile' },
      { label: 'JEE Main (All-India quota)', value: '~97 - 99 percentile' },
    ],
    admissionSteps: [
      '80% seats: MHT-CET -> Maharashtra CET Cell CAP rounds.',
      '20% seats: JEE Main (All-India quota) via CAP.',
      'M.Tech: GATE/PGCET; MCA: MAH-MCA CET.',
    ],
    placements: [
      '2024-25: highest ~Rs 72.3 LPA; average ~Rs 9.93 LPA; median ~Rs 10.9 LPA.',
      'Computer Engg average ~Rs 19.7 LPA. Recruiters: DE Shaw, Goldman Sachs, Morgan Stanley, Google, Microsoft, Bank of America, TCS, Deloitte.',
    ],
    campusLife: [
      'Hostels: boys ~Rs 22,710-70,000/yr; girls ~Rs 22,710-64,500/yr',
      'Fests: Technovanza (tech), Pratibimb (cultural); robotics & coding clubs',
      "Central Mumbai location on Matunga's education belt",
    ],
  },

  'visvesvaraya-national-institute-of-technology-nagpur': {
    overview:
      "Central India's leading NIT, strong in core engineering and architecture, with a green 215-acre campus in Nagpur.",
    established: '1960 (as VRCE)',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: 'NAAC A',
    ranking: 'NIRF 2024: #39 Engineering; #10 Architecture',
    website: 'vnit.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '215 acres',
    highlights: [
      { label: 'Established', value: '1960' },
      { label: 'NIRF Engineering', value: '#39' },
      { label: 'Campus', value: '215 acres' },
      { label: 'Avg package', value: '~Rs 10.68 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE, ECE, EEE, Mech, Chemical, Civil, Metallurgy, Mining)',
        duration: '4 yrs',
        seats: '~900',
        eligibility: '10+2 PCM 75% (65% SC/ST) + JEE Main',
        fees: '1st yr ~Rs 1.35 L; ~Rs 5.5 L total',
      },
      {
        name: 'B.Arch',
        duration: '5 yrs',
        seats: '~60',
        eligibility: '10+2 50% + JEE Main Paper 2',
        fees: '~Rs 6.95 L total',
      },
      {
        name: 'M.Tech',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'B.Tech + GATE (CCMT)',
        fees: '~Rs 1.64 L total',
      },
      {
        name: 'M.Sc / PhD',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'IIT JAM',
        fees: 'M.Sc ~Rs 61,800',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'JoSAA 2025 R1 (General) - CSE', value: 'HS 6,150 | OS 5,809' },
      { label: 'ECE', value: 'HS 10,301 | OS 9,532' },
      { label: 'EEE', value: 'HS 14,358 | OS 13,127' },
      { label: 'Mechanical', value: 'HS 18,271 | OS 19,357' },
      { label: 'Chemical', value: 'HS 26,516 | OS 26,875' },
      { label: 'Civil', value: 'HS 35,305 | OS 32,228' },
      { label: 'B.Arch', value: 'HS 398 | OS 617' },
    ],
    admissionSteps: [
      'JEE Main -> JoSAA / CSAB counselling.',
      'M.Tech: GATE -> CCMT; M.Sc: IIT JAM -> CCMN.',
    ],
    placements: [
      '2024-25: 567 placed (588 offers, 131 recruiters); highest ~Rs 34.1 LPA; average ~Rs 10.68 LPA; CSE average ~Rs 14.89 LPA.',
      'Recruiters: Morgan Stanley, Bajaj Auto, Qualcomm, Tata Motors, L&T, Amazon, JP Morgan, ABB.',
    ],
    campusLife: [
      "10 boys' + 2 girls' hostels; ~Rs 78,600-95,520/yr incl. mess",
      'Swimming pool, sports complex, 150+ clubs',
      'Fests: Aarohi (cultural), Axis (technical)',
    ],
  },

  'indian-institute-of-technology-bhu-varanasi': {
    overview:
      'Heritage IIT within Banaras Hindu University. Offers 4-year B.Tech and 5-year IDD programmes with strong placements.',
    established: '1919 (Banaras Engineering College); IIT status 2012',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: 'NAAC A++',
    ranking: 'NIRF 2025: #10 Engineering',
    website: 'iitbhu.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: "Within BHU's 1,300-acre campus",
    highlights: [
      { label: 'IIT status', value: '2012' },
      { label: 'NIRF 2025', value: '#10 Engineering' },
      { label: 'B.Tech seats', value: '~1,102' },
      { label: 'Avg package', value: '~Rs 22 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE 114, MnC 60, Electronics 86, Electrical 97, Mech 136, Civil 94, Chemical 66, Metallurgy, Mining, Ceramic, Pharma)',
        duration: '4 yrs',
        seats: '~1,102',
        eligibility: '10+2 PCM 75% + JEE Advanced',
        fees: '1st yr ~Rs 2.18 L; ~Rs 8.67 L total',
      },
      {
        name: 'B.Tech + M.Tech (IDD)',
        duration: '5 yrs',
        seats: '-',
        eligibility: 'Same',
        fees: '~Rs 10 L',
      },
      {
        name: 'M.Tech / M.Pharm',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'B.Tech 60% + GATE (COAP) / GPAT',
        fees: '~Rs 0.8 - 3.0 L',
      },
      {
        name: 'PhD',
        duration: '3-5 yrs',
        seats: '-',
        eligibility: "Master's + GATE/NET",
        fees: '~Rs 1.13 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'JoSAA 2025 (General, JEE Adv rank) - CSE', value: 'R1 1,350 | R6 1,489' },
      { label: 'Mathematics & Computing', value: '1,838 -> 1,924' },
      { label: 'Electronics', value: '2,500 -> 2,635' },
      { label: 'Electrical', value: '3,493 -> 3,537' },
      { label: 'Mechanical', value: '6,525 -> 7,286' },
      { label: 'GATE 2025 M.Tech AI', value: '~772' },
    ],
    admissionSteps: [
      'JEE Advanced -> JoSAA counselling (6 rounds).',
      'M.Tech: GATE + COAP; PhD: written test + interview.',
    ],
    placements: [
      '2024-25: 1,373 offers incl. 263 PPOs; average ~Rs 22 LPA; highest ~Rs 2.2 Cr (international); 300+ companies.',
      'Recruiters: Google, Microsoft, Goldman Sachs, Amazon, Tata Steel, Samsung, Oracle, Qualcomm.',
    ],
    campusLife: [
      "15 boys' + 3 girls' hostels; nominal hostel charges (~Rs 5,100/yr + mess)",
      'Fests: Technex (tech), Kashiyatra (cultural), Spardha (sports)',
      'Supercomputing centre; 24-hr library; ghats of Varanasi nearby',
    ],
  },

  'amity-university-noida': {
    overview:
      'Flagship Amity campus in Noida with a large engineering school, 24+ B.Tech specialisations and extensive campus life.',
    established: '2005',
    type: 'Private state university (Ritnand Balved Education Foundation)',
    affiliation: '',
    approval: 'NAAC A+',
    ranking: 'NIRF 2025: #22 University; #37 Engineering',
    website: 'amity.edu',
    contact: '',
    teachingHospital: '',
    campusSize: '~85 acres',
    highlights: [
      { label: 'Established', value: '2005' },
      { label: 'NIRF Engineering', value: '#37' },
      { label: 'Campus', value: '~85 acres' },
      { label: 'Highest package', value: '~Rs 75 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE, AI-ML, IT, ECE, EEE, Mech, Civil, Aerospace, Biotech, etc.)',
        duration: '4 yrs',
        seats: 'Large intake',
        eligibility: '10th & 12th 60%; 70% in P+M+3rd subject; JEE Main / CUET / merit',
        fees: '~Rs 1 - 2.19 L per semester; total ~Rs 9.1 - 25.7 L',
      },
      {
        name: 'B.Tech + MBA (dual)',
        duration: '5 yrs',
        seats: '-',
        eligibility: 'Same',
        fees: 'Higher',
      },
      {
        name: 'M.Tech',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'B.Tech',
        fees: 'Varies',
      },
    ],
    courseNotes: ['Merit scholarships up to 100% based on JEE/CUET/Class 12 marks.'],
    cutoffs: [
      {
        label: 'Admission basis',
        value: 'Class 12 merit (80%+ for direct), JEE Main / CUET scores + interview; no fixed rank cutoff published',
      },
    ],
    admissionSteps: [
      'Online application (Rs 1,500) -> merit on Class 12 and/or JEE Main/CUET -> PI (if shortlisted) -> fee payment.',
    ],
    placements: [
      '2024-25 (B.Tech): 700+ placed, 360+ companies; highest ~Rs 75 LPA; CSE average ~Rs 5.5 LPA.',
      'Recruiters: Capgemini, TCS, Cognizant, Accenture, DXC, Wipro, IBM, EY, Amazon.',
    ],
    campusLife: [
      'AC hostels ~Rs 1.95 L/yr (separate boys/girls)',
      '200+ clubs; fests: Amiphoria, Amity Youth Fest, Sangathan (sports)',
    ],
  },

  'national-institute-of-technology-nit-raipur': {
    overview:
      "Chhattisgarh's top engineering institute, known for mining, metallurgy and core branches alongside CSE/IT.",
    established: '1956 (Government Engineering College; NIT 2005)',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: '',
    ranking: 'NIRF 2024: #71 Engineering; #36 Architecture',
    website: 'nitrr.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '~100 acres',
    highlights: [
      { label: 'Established', value: '1956 / NIT 2005' },
      { label: 'NIRF Engineering', value: '#71' },
      { label: 'Campus', value: '~100 acres' },
      { label: 'Avg package', value: '~Rs 10.8 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE, IT, ECE, EE, Mech, Chemical, Civil, Biotech, Metallurgy, Biomedical, Mining)',
        duration: '4 yrs',
        seats: '~1,000',
        eligibility: '10+2 PCM 75% + JEE Main',
        fees: '1st yr ~Rs 1.43 L; ~Rs 5.5 L total',
      },
      {
        name: 'B.Arch',
        duration: '5 yrs',
        seats: '-',
        eligibility: 'JEE Main Paper 2',
        fees: '-',
      },
      {
        name: 'M.Tech',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'GATE (CCMT)',
        fees: '1st yr ~Rs 87,820',
      },
      {
        name: 'MCA / M.Sc / PhD',
        duration: '2-3 yrs',
        seats: '-',
        eligibility: 'NIMCET / IIT JAM',
        fees: 'MCA ~Rs 3.08 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'JoSAA 2025 (General, Other-State) - CSE', value: '12,123' },
      { label: 'IT', value: '14,591' },
      { label: 'ECE', value: '17,969' },
      { label: 'Electrical', value: '23,631' },
      { label: 'Mechanical', value: '29,821' },
      { label: 'Chemical', value: '35,946' },
      { label: 'Civil', value: '41,084' },
      { label: 'B.Arch', value: '839' },
    ],
    admissionSteps: [
      'JEE Main -> JoSAA / CSAB (50% Home State CG / 50% Other State).',
    ],
    placements: [
      '2023-24: 778 offers, ~83% placed; highest ~Rs 62 LPA; average ~Rs 10.8 LPA.',
      'Recruiters: Aditya Birla, Deloitte, Dassault Systemes, HCLTech, Reliance, Vedanta, ZS Associates.',
    ],
    campusLife: [
      "5 boys' + 3 girls' hostels; ~Rs 34,000/yr",
      'Fests: Aavartan (tech), Sanskriti (cultural), Samar (sports)',
    ],
  },

  'bhilai-institute-of-technology-bit-durg': {
    overview:
      "One of Chhattisgarh's oldest and most reputed private engineering colleges, admitting through CG-PET and JEE Main.",
    established: '1986',
    type: 'Private (Bhilai Education Trust); affiliated to CSVTU',
    affiliation: 'CSVTU',
    approval: 'AICTE; NAAC A (3.2); NBA',
    ranking: 'IIRF 2024 #73; Collegedunia #156',
    website: 'bitdurg.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '~153 acres (as reported)',
    highlights: [
      { label: 'Established', value: '1986' },
      { label: 'Campus', value: '~153 acres' },
      { label: 'B.Tech seats', value: '~720' },
      { label: 'UG median', value: '~Rs 4.16 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE, CSE-AI, Data Science, IT, ETC, EE, EEE, Mech, Civil)',
        duration: '4 yrs',
        seats: '~720',
        eligibility: '10+2 PCM 45% + CG-PET / JEE Main',
        fees: '~Rs 3.06 L total (state fee)',
      },
      {
        name: 'M.Tech',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'GATE / merit',
        fees: '~Rs 1.43 L',
      },
      {
        name: 'MBA / MCA',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'CG-PET/MAT / graduation',
        fees: 'MBA ~Rs 2.31 L; MCA ~Rs 1.35 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CG-PET 2024 R1 (General, score/percentile) - CSE', value: '91.67' },
      { label: 'CSE-AI', value: '85.40' },
      { label: 'Data Science', value: '81.36' },
      { label: 'IT', value: '70.90' },
      { label: 'Civil', value: '62.32' },
      { label: 'Mechanical', value: '38.47' },
    ],
    admissionSteps: ['CG Vyapam PET / JEE Main -> Chhattisgarh DTE online counselling.'],
    placements: [
      '2024 (NIRF): UG median ~Rs 4.16 LPA; PG median ~Rs 4 LPA.',
      'Recruiters: TCS, Tech Mahindra, Accenture, Wipro, Tata Steel, Capgemini, Bajaj.',
    ],
    campusLife: [
      'Hostels: 350 boys, 190 girls; ~Rs 40,000/semester',
      'Technical & cultural clubs; annual fest',
    ],
  },

  'national-institute-of-technology-nit-durgapur': {
    overview:
      'Leading NIT of eastern India, with a large green campus in the steel city of Durgapur.',
    established: '1960 (REC Durgapur)',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: '',
    ranking: 'NIRF 2024: #44 Engineering; #92 Overall',
    website: 'nitdgp.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '187 acres',
    highlights: [
      { label: 'Established', value: '1960' },
      { label: 'NIRF Engineering', value: '#44' },
      { label: 'Campus', value: '187 acres' },
      { label: 'Avg package', value: '~Rs 12.16 LPA' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE, MnC, ECE, EE, Mech, Chemical, Civil, Biotech, Metallurgy...)',
        duration: '4 yrs',
        seats: '~900',
        eligibility: '10+2 PCM 75% + JEE Main',
        fees: '~Rs 7.45 L total',
      },
      {
        name: 'M.Tech',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'GATE (CCMT)',
        fees: '1st yr ~Rs 1.19 L',
      },
      {
        name: 'MBA',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'CAT/MAT + GD/PI',
        fees: '1st yr ~Rs 1.24 L',
      },
      {
        name: 'M.Sc / MCA / PhD',
        duration: '2-3 yrs',
        seats: '-',
        eligibility: 'IIT JAM / NIMCET',
        fees: 'M.Sc 1st yr ~Rs 63,700',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'JoSAA 2025 (General) - CSE', value: 'HS 10,493 | OS 8,596' },
      { label: 'Maths & Computing', value: 'HS 12,429 | OS 10,872' },
      { label: 'ECE', value: 'HS 14,676 | OS 12,334' },
      { label: 'EE', value: 'HS 19,950 | OS 18,049' },
      { label: 'Mechanical', value: 'HS 26,998 | OS 24,706' },
      { label: 'Civil', value: 'HS 36,902 | OS 37,328' },
    ],
    admissionSteps: [
      'JEE Main -> JoSAA / CSAB.',
      'M.Tech via CCMT; MBA via CAT/MAT + GD/PI.',
    ],
    placements: [
      'Latest report: highest ~Rs 80 LPA; average ~Rs 12.16 LPA; ~77.7% placed.',
      '2024: highest ~Rs 51 LPA; median ~Rs 8.1 LPA; 200+ companies.',
      'Recruiters: TCS, Microsoft, PwC, ICICI Bank, JP Morgan, Oracle, Google, IBM.',
    ],
    campusLife: [
      "10 boys' + 4 girls' hostels; ~Rs 10,000/semester (room)",
      'Fests: Aarohan (tech), Recursion (coding), Mukti (cultural)',
    ],
  },

  'heritage-institute-of-technology': {
    overview:
      "One of Kolkata's best private engineering colleges, with a sizeable CSE/IT intake and admission mainly through WBJEE.",
    established: '2001',
    type: 'Private autonomous (Kalyan Bharti Trust); affiliated to MAKAUT',
    affiliation: 'MAKAUT',
    approval: 'AICTE; NAAC A; NBA',
    ranking: 'IIRF #108 (Engineering)',
    website: 'heritageit.edu',
    contact: '',
    teachingHospital: '',
    campusSize: '~20 acres in East Kolkata',
    highlights: [
      { label: 'Established', value: '2001' },
      { label: 'B.Tech seats', value: '~1,000' },
      { label: 'Campus', value: '~20 acres' },
      { label: 'Placement rate', value: '~80% UG (NIRF)' },
    ],
    courses: [
      {
        name: 'B.Tech (CSE, IT, AI-ML, Data Science, IoT & Cyber Security, ECE, EE, AEIE, Mech, Civil, Chemical, Biotech)',
        duration: '4 yrs',
        seats: '~1,000',
        eligibility: '10+2 PCM 45% + WBJEE (80%) / JEE Main (10%) / management (10%)',
        fees: '~Rs 1.72 L/yr; ~Rs 5.89 L total',
      },
      {
        name: 'B.Tech Lateral',
        duration: '3 yrs',
        seats: '-',
        eligibility: 'Diploma + JELET',
        fees: '~Rs 1.72 L/yr',
      },
      {
        name: 'M.Tech / MCA / MBA',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'GATE/PGET; JECA; MAT/CAT',
        fees: 'M.Tech ~Rs 1.3-1.5 L/yr; MCA ~Rs 1.72 L/yr',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'WBJEE 2025 (General) - CSE', value: '5,134 - 5,906' },
      { label: 'AI-ML', value: '5,889 - 6,721' },
      { label: 'Data Science', value: '7,195 - 9,170' },
      { label: 'IT', value: '7,214 - 8,543' },
      { label: 'ECE', value: '11,585 - 15,730' },
      { label: 'Electrical', value: '16,195 - 23,064' },
      { label: 'Mechanical', value: '27,909 - 43,698' },
      { label: 'JEE Main 2025 - CSE', value: '64,575 - 75,666 (CRL)' },
    ],
    admissionSteps: [
      'WBJEE rank -> WBJEEB counselling (80%); JEE Main -> WBJEEB (10%); management quota direct (10%).',
    ],
    placements: [
      '2024-25 (NIRF): 763 of 967 UG placed (~80%); median ~Rs 5 LPA.',
      '2024 B.Tech: highest ~Rs 11.3 LPA; average ~Rs 4.62 LPA.',
      'Recruiters: TCS, Cognizant, Infosys, Wipro, Capgemini, Accenture, IBM, Tech Mahindra, Amazon.',
    ],
    campusLife: [
      'Separate hostels (priority by distance)',
      '250-seat AC library, swimming pool, football, cricket, basketball',
      'Collegedunia student rating 4.2/5; ragging-free campus',
    ],
  },
};
