/** Clean curated MBA college research (12). */
export const mba = {
  'indian-institute-of-management-iim-bangalore': {
    overview:
      "One of India's top-three B-schools, known for its stone-walled campus by architect B. V. Doshi and strong consulting and finance placements.",
    established: '1973',
    type: 'Institute of National Importance (IIM Act 2017)',
    affiliation: '',
    approval: 'EQUIS',
    ranking: 'NIRF 2025 (Management) #2; FT Global MBA 2025 #57',
    website: 'iimb.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '100 acres, designed by B. V. Doshi',
    highlights: [
      { label: 'Established', value: '1973' },
      { label: 'NIRF 2025', value: '#2 Management' },
      { label: 'Campus', value: '100 acres' },
      { label: 'Avg package', value: '~Rs 32.6 LPA' },
    ],
    courses: [
      {
        name: 'MBA (PGP)',
        duration: '2 yrs',
        seats: '~500+',
        eligibility: "Bachelor's 50% (45% SC/ST/PwD) + CAT",
        fees: '~Rs 26.3 L total (incl. hostel)',
      },
      {
        name: 'MBA Business Analytics (PGPBA)',
        duration: '2 yrs',
        seats: '-',
        eligibility: "Bachelor's 50% (45% SC/ST/PwD) + CAT",
        fees: '~Rs 20+ L',
      },
      {
        name: 'EPGP (1-yr MBA)',
        duration: '1 yr',
        seats: '~75',
        eligibility: '5+ yrs exp + GMAT/GRE',
        fees: '~Rs 30+ L',
      },
      {
        name: 'PGPEM / PGPPM / PhD',
        duration: '2 yrs / 1 yr / 4-5 yrs',
        seats: '-',
        eligibility: "Working professionals / Master's",
        fees: 'Varies',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CAT - General (aggregate, shortlist)', value: '85 percentile; sectional 75-80 (actual calls usually 99+)' },
      { label: 'NC-OBC / EWS', value: '75 percentile' },
      { label: 'SC', value: '70 percentile' },
      { label: 'ST', value: '65 percentile' },
    ],
    admissionSteps: [
      'CAT -> shortlisting on CAT + academics.',
      'WAT + Personal Interview.',
      'Final composite: CAT 25%, PI 40%, WAT 10%, Work-ex 10%, Academics 15%.',
    ],
    placements: [
      'Final placements (latest reported): 596 students, 664 offers from 177 companies; average ~Rs 32.6 LPA; 35% new recruiters.',
      'Consulting ~45% of offers. Top recruiters: Accenture (94), BCG (27), Bain (23), EY-Parthenon (22), Kearney (13).',
    ],
    campusLife: [
      '16 hostel blocks (A-P), single occupancy furnished rooms',
      '55,000 sq ft library with 1.6 lakh+ books',
      'Cricket, football, basketball, badminton, jogging track; fests: Unmaad (cultural), Vista (business)',
    ],
  },

  't-a-pai-management-institute-manipal': {
    overview:
      "Established by T. A. Pai and the Manipal group, TAPMI is one of South India's leading private B-schools with a fully residential campus and strong BFSI placements.",
    established: '1980',
    type: 'Private autonomous (Manipal Academy of Higher Education)',
    affiliation: 'Manipal Academy of Higher Education',
    approval: 'AACSB, AMBA; AICTE-approved',
    ranking: 'NIRF 2025 (Management) #39',
    website: 'tapmi.edu.in',
    contact: '',
    teachingHospital: '',
    campusSize: '44 acres on a hillock at Manipal',
    highlights: [
      { label: 'Established', value: '1980' },
      { label: 'NIRF 2025', value: '#39 Management' },
      { label: 'Accreditation', value: 'AACSB, AMBA' },
      { label: 'Campus', value: '44 acres' },
    ],
    courses: [
      {
        name: 'MBA (General / Marketing / HRM / IB / DS & AI)',
        duration: '2 yrs',
        seats: '420',
        eligibility: "Bachelor's 60% + CAT/XAT/GMAT/NMAT",
        fees: '~Rs 20.1 L total',
      },
      {
        name: 'MBA Banking & Financial Services',
        duration: '2 yrs',
        seats: '120',
        eligibility: "Bachelor's 60% + CAT/XAT/GMAT/NMAT",
        fees: '~Rs 24.4 L total',
      },
      {
        name: 'Integrated Programme in Management (IPM)',
        duration: '5 yrs',
        seats: '-',
        eligibility: 'Class 12 with 60%',
        fees: '~Rs 28.9 L',
      },
      {
        name: 'BBA (Hons.)',
        duration: '4 yrs',
        seats: '-',
        eligibility: 'Class 12',
        fees: '~Rs 16.3 L',
      },
    ],
    courseNotes: ['Hostel ~Rs 3.45 L per year (fully residential).'],
    cutoffs: [
      { label: 'CAT / XAT (freshers)', value: '90 percentile and above typically' },
      { label: 'Experienced (12+ months)', value: 'Relaxed percentile with higher work-ex weight' },
    ],
    admissionSteps: [
      'Apply via TAPMI portal with CAT/XAT/GMAT/NMAT score.',
      'Shortlist -> GD/WAT + Personal Interview.',
      'Weightage: GD/WAT/PI 45%, entrance 30%, work-ex 15%, academics 10%.',
    ],
    placements: [
      '2025: 100% placement; average ~Rs 13.08 LPA; highest ~Rs 32.77 LPA (MBA) / Rs 26.25 LPA (BFS).',
      '100+ companies; BFSI ~39% of offers. Recruiters: Deloitte, EY, JPMorgan Chase, ICICI Bank, Accenture, Mercedes-Benz.',
    ],
    campusLife: [
      'Fully residential; Bloomberg trading lab, Leadership Assessment Centre',
      'Annual fest: Atharva',
      'Merit scholarships up to 100% tuition waiver',
    ],
  },

  'symbiosis-institute-of-buisness-management-bangalore': {
    overview:
      "Bengaluru campus of Symbiosis in the Electronic City IT hub. Admission through SNAP followed by Symbiosis' GE-PIWAT process.",
    established: '2008',
    type: 'Constituent of Symbiosis International (Deemed University), Pune',
    affiliation: 'Symbiosis International (Deemed University)',
    approval: 'UGC / AICTE; NAAC (SIU) A++ (3.5)',
    ranking: 'Outlook 2024: #54; NIRF counted under SIU',
    website: 'sibm.edu.in',
    contact: '',
    teachingHospital: '',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '2008' },
      { label: 'MBA seats', value: '240' },
      { label: 'NAAC (SIU)', value: 'A++' },
      { label: 'Avg package', value: '~Rs 14.53 LPA' },
    ],
    courses: [
      {
        name: 'MBA',
        duration: '2 yrs',
        seats: '240',
        eligibility: "Bachelor's 50% (45% SC/ST) + SNAP",
        fees: '~Rs 26.59 L total (Yr1 Rs 14.09 L + Yr2 Rs 12.50 L); NRI ~Rs 40.2 L',
      },
      {
        name: 'MBA Business Analytics',
        duration: '2 yrs',
        seats: '30',
        eligibility: "Bachelor's 50% + SNAP",
        fees: '~Rs 26.59 L',
      },
      {
        name: 'Executive MBA',
        duration: '2 yrs',
        seats: 'Limited',
        eligibility: 'Work experience; no SNAP',
        fees: '~Rs 5.8 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'SNAP - MBA (General)', value: '89+ percentile' },
      { label: 'SNAP - MBA Business Analytics', value: '83+ percentile' },
    ],
    admissionSteps: [
      'SNAP Test (Dec 13, 19, 26, 2026 for 2027-29).',
      'Shortlist -> Group Exercise, Personal Interaction & Writing Ability Test (GE-PIWAT), Jan-Mar 2027.',
      'Final merit: SNAP (50) + GE-PIWAT (50).',
    ],
    placements: [
      '2025 final: highest ~Rs 23.5 LPA; average ~Rs 14.53 LPA; median ~Rs 14 LPA; 195+ companies.',
      'Recruiters: JP Morgan Chase, Morgan Stanley, Deloitte, ITC, PwC, Accenture, Capgemini.',
    ],
    campusLife: [
      'Residential hostels on campus',
      'Clubs across marketing, finance, HR, analytics; fest & industry conclaves',
      "Located amid Electronic City's tech corporates",
    ],
  },

  'jamnalal-bajaj-institute-of-management-studies-mumbai': {
    overview:
      "Mumbai University's management department, called the 'CEO factory'. Offers one of India's best ROI MBAs (MMS) with fees under Rs 10 lakh.",
    established: '1965',
    type: 'Government-aided autonomous (University of Mumbai)',
    affiliation: 'University of Mumbai',
    approval: 'AICTE',
    ranking: 'Outlook #10; IIRF #6 (2025)',
    website: 'jbims.edu',
    contact: '',
    teachingHospital: '',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '1965' },
      { label: 'MMS seats', value: '160' },
      { label: 'Fees', value: '~Rs 8.34 L total' },
      { label: 'Avg package', value: '~Rs 26.48 LPA' },
    ],
    courses: [
      {
        name: 'MMS (MBA equivalent)',
        duration: '2 yrs',
        seats: '160',
        eligibility: "Bachelor's 50% (45% reserved) + MAH-MBA CET / CAT / CMAT",
        fees: '~Rs 8.34 L total',
      },
      {
        name: 'M.Sc. Finance',
        duration: '2 yrs',
        seats: '42',
        eligibility: "Bachelor's + CAT/MAH-CET",
        fees: '~Rs 6 L',
      },
      {
        name: 'MHRD',
        duration: '2 yrs',
        seats: '-',
        eligibility: "Bachelor's",
        fees: '~Rs 7 L',
      },
      {
        name: 'Part-time MMS / PhD',
        duration: '3 yrs',
        seats: '-',
        eligibility: 'Working professionals / PG',
        fees: 'Nominal',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'MMS - MAH-CET (General)', value: '99.93 - 99.99 percentile' },
      { label: 'MMS - CAT (All-India)', value: '96+ percentile' },
      { label: 'OBC (MAH-CET)', value: '~99.81 percentile' },
      { label: 'SC (MAH-CET)', value: '~99.51 percentile' },
      { label: 'M.Sc Finance', value: 'CAT 95+ / MAH-CET 97+' },
    ],
    admissionSteps: [
      'State seats: MAH-MBA CET -> DTE Maharashtra CAP rounds (no GD/PI).',
      'All-India seats: CAT/CMAT scores via CAP.',
    ],
    placements: [
      '2025 final (MMS): highest ~Rs 55.6 LPA; average ~Rs 26.48 LPA; median ~Rs 26.15 LPA; 100% placed; 65+ recruiters.',
      'Sector split: BFSI 42%, Tech 18%, Consulting 16%, Mfg 12%, FMCG 8%.',
      'Recruiters: Goldman Sachs, McKinsey, BCG, J.P. Morgan, HSBC, HUL, P&G, Amazon, Microsoft.',
    ],
    campusLife: [
      'South Mumbai location near Nariman Point business district',
      'No in-house hostel (limited University hostel seats)',
      'Committees: Placement, E-Cell, CSR, Alumni; fest: Nexus; 40,000+ book library',
    ],
  },

  's-p-jain-institute-of-management-and-research': {
    overview:
      'Premier Mumbai B-school known for its values-based, social-sensitivity curriculum and strong placements.',
    established: '1981',
    type: 'Private autonomous (Bharatiya Vidya Bhavan)',
    affiliation: '',
    approval: 'Triple crown - AACSB, AMBA, EQUIS',
    ranking: 'NIRF 2025 (Management) #20; FT Masters in Management 2025 #35 globally',
    website: 'spjimr.org',
    contact: '',
    teachingHospital: '',
    campusSize: "45-acre Bhavan's campus, Andheri",
    highlights: [
      { label: 'Established', value: '1981' },
      { label: 'NIRF 2025', value: '#20 Management' },
      { label: 'Accreditation', value: 'AACSB, AMBA, EQUIS' },
      { label: 'Avg package', value: '~Rs 33.75 LPA' },
    ],
    courses: [
      {
        name: 'PGDM',
        duration: '2 yrs',
        seats: '240',
        eligibility: "Bachelor's 50% + CAT/GMAT",
        fees: '~Rs 24.86 L',
      },
      {
        name: 'PGDM (Business Management)',
        duration: '2 yrs',
        seats: '120',
        eligibility: "Bachelor's 50% + CAT/GMAT",
        fees: '~Rs 24.86 L',
      },
      {
        name: 'PGPM (18 months)',
        duration: '1.5 yrs',
        seats: '-',
        eligibility: '3+ yrs work-ex + CAT/GMAT',
        fees: '~Rs 22.66 L',
      },
      {
        name: 'PGEMP',
        duration: '21 months',
        seats: '-',
        eligibility: 'Working professionals',
        fees: '~Rs 10.46 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CAT - qualifying (domestic)', value: '85 overall, 75 per section' },
      { label: 'Actual shortlist', value: 'Usually 95+ percentile' },
    ],
    admissionSteps: [
      'Apply with CAT/GMAT score + profile; shortlist based on profile.',
      'Interviews (Jan-Feb) -> final offer; session starts June.',
    ],
    placements: [
      'Latest final: 100% placement; average ~Rs 33.75 LPA; median ~Rs 32.85 LPA; highest ~Rs 75 LPA (PGDM).',
      'Recruiters: McKinsey, BCG, Deloitte, EY, KPMG, PwC, Accenture.',
    ],
    campusLife: [
      'Fully residential; sports courts, gym, yoga',
      'Library 29,000+ books; Design Thinking Lab',
      'Botanical garden (250+ species); 5 min from metro',
    ],
  },

  'indian-institute-of-management-iim-lucknow': {
    overview:
      'One of the older IIMs, known for its PGP and the unique PGP in Agri-Business Management. Strong consulting and finance placements.',
    established: '1984',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: 'AACSB',
    ranking: 'NIRF 2025 (Management) #5; FT Global MBA 2025 #57',
    website: 'iiml.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '200+ acres; Noida campus for executive programmes',
    highlights: [
      { label: 'Established', value: '1984' },
      { label: 'NIRF 2025', value: '#5 Management' },
      { label: 'Campus', value: '200+ acres' },
      { label: 'Avg package', value: '~Rs 33.2 LPA' },
    ],
    courses: [
      {
        name: 'PGP (MBA)',
        duration: '2 yrs',
        seats: '~430',
        eligibility: "Bachelor's 50% + CAT",
        fees: '~Rs 20.75 L (+ hostel/mess ~Rs 8.15 L over 2 yrs)',
      },
      {
        name: 'PGP-ABM',
        duration: '2 yrs',
        seats: '60',
        eligibility: "Bachelor's 50% + CAT",
        fees: '~Rs 20.75 L',
      },
      {
        name: 'PGP-Sustainable Management',
        duration: '2 yrs',
        seats: '~50',
        eligibility: "Bachelor's + 24 mo work-ex + CAT",
        fees: '~Rs 20.75 L',
      },
      {
        name: 'IPMX (Noida)',
        duration: '1 yr',
        seats: '-',
        eligibility: '5+ yrs exp + GMAT/GRE/CAT',
        fees: '~Rs 26.25 L',
      },
      {
        name: 'FPM / BS Business Analytics',
        duration: '4-5 yrs / 4 yrs',
        seats: '-',
        eligibility: "Master's / Class 12",
        fees: 'FPM ~Rs 7.5 L; BS ~Rs 20 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CAT - PGP/ABM (General) shortlist', value: '90 overall, 85 each section (final calls typically 98-99+)' },
      { label: 'PGP-SM', value: '80 percentile' },
    ],
    admissionSteps: [
      'Stage 1 shortlist: CAT 60%, Class 12 10%, graduation 10%, work-ex 10%, diversity 10%.',
      'Stage 2 final: PI 40%, CAT 30%, WAT 10%, academics 10%, work-ex 5%, diversity 5%; min PI 12/40.',
    ],
    placements: [
      'Latest final: 559 placed with 580+ offers; average ~Rs 33.2 LPA; median ~Rs 32.9 LPA; highest domestic ~Rs 1 Cr.',
      'Consulting ~38%. Recruiters: McKinsey, BCG, Deloitte, PwC, Accenture, Goldman Sachs.',
    ],
    campusLife: [
      'Mandatory residential hostels (separate male/female)',
      'Sports complex incl. swimming pool; central library',
      'Fest: Manfest-Varchasva',
    ],
  },

  'institute-of-management-technology-imt-ghaziabad': {
    overview:
      'Flagship campus of the IMT group (Ghaziabad, Nagpur, Hyderabad, Dubai). Known for PGDM with strong marketing and BFSI placements.',
    established: '1980',
    type: 'Private autonomous; AICTE-approved',
    affiliation: '',
    approval: 'AACSB, AMBA',
    ranking: 'NIRF 2025 (Management) #30',
    website: 'imt.edu',
    contact: '',
    teachingHospital: '',
    campusSize: '14 acres, Wi-Fi enabled',
    highlights: [
      { label: 'Established', value: '1980' },
      { label: 'NIRF 2025', value: '#30 Management' },
      { label: 'Campus', value: '14 acres' },
      { label: 'Avg package', value: '~Rs 16.25 LPA' },
    ],
    courses: [
      {
        name: 'PGDM (General)',
        duration: '2 yrs',
        seats: '~360',
        eligibility: "Bachelor's 50% + CAT/XAT/GMAT",
        fees: '~Rs 23 L (incl. hostel)',
      },
      {
        name: 'PGDM Marketing / Finance / HR / BFS',
        duration: '2 yrs',
        seats: '-',
        eligibility: "Bachelor's 50% + CAT/XAT/GMAT",
        fees: '~Rs 23 L',
      },
      {
        name: 'PGDM Dual Country (DCP - India + Dubai)',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'Same',
        fees: '~Rs 10.03 L + AED 87,675',
      },
      {
        name: 'Executive PGDM',
        duration: '1.5 yrs',
        seats: '-',
        eligibility: '3+ yrs work-ex',
        fees: '~Rs 21 L',
      },
      {
        name: 'FPM',
        duration: '4 yrs',
        seats: '-',
        eligibility: "Master's 60%",
        fees: '-',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CAT (General)', value: '~90 percentile' },
      { label: 'XAT (General)', value: '~90 percentile' },
    ],
    admissionSteps: [
      'Apply with CAT/XAT/GMAT.',
      'Group Activity + Personal Interview; PI weighted highest, followed by entrance score, academics & work-ex.',
    ],
    placements: [
      '2025 PGDM: highest ~Rs 41.55 LPA; average ~Rs 16.25 LPA; median ~Rs 15 LPA; top-100 average ~Rs 24.32 LPA; 190 recruiters (57 new).',
      'Recruiters: Goldman Sachs, Britannia, HCL Tech, HSBC, Havells, GSK, Dabur.',
      'Summer: highest stipend ~Rs 2.25 L/month; average ~Rs 60,000/month.',
    ],
    campusLife: [
      'Two hostels (main campus + 3 km), AC shared rooms',
      'Finance lab, library, gym, cricket/football/badminton',
      'Clubs: marketing, finance, HR, analytics, consulting, cultural; annual fests',
      'Scholarships: 100% tuition waiver for family income <= Rs 8 L; merit 25-30%',
    ],
  },

  'indian-institute-of-management-iim-raipur': {
    overview:
      'A second-generation IIM with a large new campus in Naya Raipur and fast-improving rankings.',
    established: '2010',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: '',
    ranking: 'NIRF 2025 (Management) #15',
    website: 'iimraipur.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '203 acres at Atal Nagar',
    highlights: [
      { label: 'Established', value: '2010' },
      { label: 'NIRF 2025', value: '#15 Management' },
      { label: 'Campus', value: '203 acres' },
      { label: 'Median package', value: '~Rs 18.4 LPA' },
    ],
    courses: [
      {
        name: 'PGP (MBA)',
        duration: '2 yrs',
        seats: '~331',
        eligibility: "Bachelor's 60% (Gen) + CAT",
        fees: '~Rs 21.4 L',
      },
      {
        name: 'EPGP (1-yr)',
        duration: '1 yr',
        seats: '60',
        eligibility: "Bachelor's + 3 yrs work-ex",
        fees: '~Rs 14.95 L',
      },
      {
        name: 'EPGP-HRM',
        duration: '1 yr',
        seats: '-',
        eligibility: '3 yrs work-ex',
        fees: '~Rs 13.25 L',
      },
      {
        name: 'PhD',
        duration: '3+ yrs',
        seats: '-',
        eligibility: 'PG',
        fees: '~Rs 10.35 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CAT - General (minimum)', value: '94 overall + 73 each section' },
      { label: 'Actual shortlist (General)', value: 'Usually 96+ percentile' },
    ],
    admissionSteps: [
      'Composite out of 150: CAT index 50, PI 40, Class X 15, Class XII 15, work-ex 15, gender diversity 8, profile 5, academic diversity 2.',
    ],
    placements: [
      '2025: average ~Rs 18.8 LPA; median ~Rs 18.4 LPA; highest ~Rs 34.3 LPA; 166 recruiters.',
      'Top sectors: BFSI, consulting, IT, FMCG.',
    ],
    campusLife: [
      'Fully residential; single rooms with attached washrooms',
      'Sports facilities, library, auditorium, bank/ATM on campus',
    ],
  },

  'amity-university-raipur': {
    overview:
      'Chhattisgarh campus of the Amity group; Amity Business School offers MBA with multiple specialisations and merit scholarships.',
    established: '2014',
    type: 'Private state university (Amity Education Group)',
    affiliation: '',
    approval: 'UGC recognised',
    ranking: 'India Today #67 (overall); IIRF #82 (2025)',
    website: 'amity.edu/raipur',
    contact: '',
    teachingHospital: '',
    campusSize: '50 acres',
    highlights: [
      { label: 'Established', value: '2014' },
      { label: 'Campus', value: '50 acres' },
      { label: 'MBA fees', value: '~Rs 4.4 L total' },
      { label: 'Avg package', value: '~Rs 6 LPA' },
    ],
    courses: [
      {
        name: 'MBA',
        duration: '2 yrs',
        seats: '-',
        eligibility: "Bachelor's (50%) + CAT/MAT/CMAT or Amity test",
        fees: '~Rs 4.4 L total',
      },
      {
        name: 'MBA (International Business)',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'Same',
        fees: '~Rs 4.4 L',
      },
      {
        name: 'MBA (Marketing & Sales) / MBA (HR)',
        duration: '2 yrs',
        seats: '-',
        eligibility: 'Same',
        fees: '~Rs 4.4 L',
      },
    ],
    courseNotes: [
      'Scholarships: 100% for 90+ %ile (CAT/MAT) or 650+ GMAT; 50% for 85+; 25% for 75+.',
    ],
    cutoffs: [
      { label: 'Direct admission', value: '~70 percentile in CAT/MAT' },
      { label: 'Other routes', value: "CMAT / Amity's own test + GD/PI" },
    ],
    admissionSteps: ['Online application (fee Rs 1,500) -> entrance score -> GD + PI -> offer.'],
    placements: ['2025 MBA: highest ~Rs 14 LPA; average ~Rs 6 LPA (Collegedunia).'],
    campusLife: [
      'Hostel ~Rs 63,000 - 1,26,000 per yr; 2,100+ capacity; gym, mess, laundry',
      'Fests: Sangathan (sports), AmiSpark (cultural); technical, cultural & E-cell clubs',
    ],
  },

  'indian-institute-of-management-iim-calcutta': {
    overview:
      "India's first IIM, famous for finance placements and the scenic Joka campus. Alumni include Indra Nooyi.",
    established: '1961 (first IIM)',
    type: 'Institute of National Importance',
    affiliation: '',
    approval: 'Triple crown (AACSB, AMBA, EQUIS); only Indian CEMS member',
    ranking: 'NIRF 2025 (Management) #7; FT Global MBA 2025 #49',
    website: 'iimcal.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '135 acres with 7 lakes',
    highlights: [
      { label: 'Established', value: '1961' },
      { label: 'NIRF 2025', value: '#7 Management' },
      { label: 'Campus', value: '135 acres, 7 lakes' },
      { label: 'Avg package', value: '~Rs 36 LPA' },
    ],
    courses: [
      {
        name: 'MBA',
        duration: '2 yrs',
        seats: '~480',
        eligibility: "Bachelor's 50% + CAT",
        fees: '~Rs 27 L',
      },
      {
        name: 'PGDBA (with ISI & IIT Kharagpur)',
        duration: '2 yrs',
        seats: '-',
        eligibility: '10+2+4 with 6.5 CGPA + CAT',
        fees: '~Rs 25 L',
      },
      {
        name: 'MBAEx',
        duration: '1 yr',
        seats: '-',
        eligibility: '5+ yrs work-ex + GMAT/GRE',
        fees: '~Rs 33.5 L',
      },
      {
        name: 'PGPEX-VLM',
        duration: '1 yr',
        seats: '-',
        eligibility: '5+ yrs exp',
        fees: '~Rs 13.5 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CAT 2024 - Open', value: 'Overall 85, VARC 80, DILR 80, QA 75' },
      { label: 'EWS / OBC', value: 'Overall 75, VARC 70, DILR 65, QA 65' },
      { label: 'SC', value: 'Overall 70; sectional 60-65' },
      { label: 'ST', value: 'Overall 65; sectional 55' },
    ],
    admissionSteps: [
      'Shortlist on CAT (sectional + overall) + academics.',
      'WAT + PI; final: PI 48%, CAT 30%, WAT 8%, work-ex 8%, academic diversity 6%.',
    ],
    placements: [
      'Latest final (2024-26): 458 placed, 542 offers, 202 recruiters; average ~Rs 36 LPA; median ~Rs 35 LPA; highest domestic ~Rs 1.45 Cr.',
      'Summer: average stipend ~Rs 1.89 L/month; highest ~Rs 3.67 L/month.',
      'Recruiters: Goldman Sachs, Barclays, Kearney, Google, EY, Nestle, ITC, Aditya Birla Group.',
    ],
    campusLife: [
      'Hostels: Old (co-ed), White, New; family housing for MBAEx',
      'Lakeside campus, sports complex; fests: Intaglio (business), Carpe Diem (cultural)',
    ],
  },

  'indian-institute-of-foreign-trade-iift-kolkata': {
    overview:
      "Kolkata campus of IIFT, India's premier institute for international business and trade, with a common MBA (IB) admission alongside Delhi.",
    established: '2006 (Kolkata campus); IIFT founded 1963',
    type: 'Deemed to be University, Ministry of Commerce',
    affiliation: '',
    approval: 'NAAC A+ (3.2)',
    ranking: 'NIRF 2025 Management ~#21 (IIFT)',
    website: 'iift.ac.in',
    contact: '',
    teachingHospital: '',
    campusSize: '~7 acres, 1583 Madurdaha, Chowbagha Road',
    highlights: [
      { label: 'Kolkata campus', value: '2006' },
      { label: 'MBA (IB) seats', value: '253 (Kolkata)' },
      { label: 'NIRF', value: '~#21 Management (IIFT)' },
      { label: 'Median package', value: '~Rs 26 LPA' },
    ],
    courses: [
      {
        name: 'MBA (International Business)',
        duration: '2 yrs',
        seats: '253 (Kolkata)',
        eligibility: "Bachelor's 50% + CAT (IIFT uses CAT since 2024)",
        fees: '~Rs 21.42 L',
      },
      {
        name: 'MA Economics',
        duration: '2 yrs',
        seats: '-',
        eligibility: "Bachelor's",
        fees: '~Rs 2.06 L',
      },
      {
        name: 'PhD / part-time programmes',
        duration: '-',
        seats: '-',
        eligibility: '-',
        fees: '-',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'CAT - General (male)', value: '~96-97 percentile (estimate)' },
      { label: 'General (female)', value: '~95-96' },
      { label: 'OBC-NCL', value: '~93-95' },
      { label: 'SC', value: '~88-91' },
      { label: 'ST', value: '~82-86' },
    ],
    admissionSteps: [
      'CAT score -> shortlist -> GD + PI.',
      'Weightage: CAT 48%, GD 21%, PI 22%, gender diversity 3%, academic diversity 3%, work-ex 3%.',
    ],
    placements: [
      '2025 (Delhi + Kolkata): average ~Rs 31.3 LPA; median ~Rs 26 LPA; highest domestic ~Rs 72 LPA; highest international ~Rs 1.23 Cr; 135 recruiters.',
      'Top domains: Sales & Marketing 22%, Consulting 20%.',
    ],
    campusLife: [
      'Separate hostels with mess; sports (tennis, cricket, basketball), gym',
      '500-seat auditorium, labs, library',
      '41+ international exchange partners',
    ],
  },

  'international-management-institute-imi-kolkata': {
    overview:
      'Eastern campus of the IMI network (Delhi, Bhubaneswar, Kolkata), known for a compact city campus and PGDM with multiple specialisations.',
    established: '2010',
    type: 'Private (RP-Sanjiv Goenka Group)',
    affiliation: '',
    approval: 'AICTE; AIU equivalence; NBA',
    ranking: 'IIRF 2025 #20; TOI 2026 #83',
    website: 'imik.edu.in',
    contact: '',
    teachingHospital: '',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '2010' },
      { label: 'PGDM seats', value: '~120' },
      { label: 'Fees', value: '~Rs 16.94 L total' },
      { label: 'Highest package', value: '~Rs 16.42 LPA' },
    ],
    courses: [
      {
        name: 'PGDM',
        duration: '2 yrs',
        seats: '~120',
        eligibility: "Bachelor's 50% + CAT/XAT/GMAT/CMAT",
        fees: '~Rs 16.94 L total',
      },
      {
        name: 'PGDM (Part-time)',
        duration: '-',
        seats: '-',
        eligibility: 'Working professionals',
        fees: '~Rs 2.65 L 1st yr',
      },
      {
        name: 'FPM / PG Diploma Economics',
        duration: '4 yrs / 2 yrs',
        seats: '-',
        eligibility: "PG / Bachelor's",
        fees: 'FPM ~Rs 2.87 L yr1',
      },
    ],
    courseNotes: [
      'Specialisations: Marketing, Finance, HR, Operations, Analytics, IT, Entrepreneurship.',
    ],
    cutoffs: [{ label: 'CAT / XAT (General)', value: '~75 - 80 percentile' }],
    admissionSteps: [
      'Apply with CAT/XAT/GMAT/CMAT -> shortlist -> WAT + Personal Interview -> composite merit.',
    ],
    placements: [
      'Latest: 187 students placed; highest ~Rs 16.42 LPA; average ~Rs 13.06 LPA; median ~Rs 12.49 LPA.',
      'Recruiters: Amazon, Deloitte, Tech Mahindra, PwC, Cognizant, Genpact, TCS, Wipro, Gartner.',
    ],
    campusLife: [
      'Separate hostels ~Rs 1 - 2.25 L; Wi-Fi, laundry, mess',
      'Digital library, IT labs, auditorium, gym',
      'Clubs: literary, sports, cultural, finance',
    ],
  },
};
