/** Clean curated medical college research (17). */
export const medical = {
  'kanachur-institute-of-medical-sciences': {
    overview:
      'A young private medical college run by the Kanachur Islamic Education Trust at Natekal on the outskirts of Mangalore. Along with MBBS it offers MD/MS, B.Sc allied health, Nursing, BPT, B.Pharm and BAMS within the same group campus.',
    established: '2016 (Collegedunia lists the Kanachur group as 2019)',
    type: 'Private, self-financed',
    affiliation: 'Rajiv Gandhi University of Health Sciences (RGUHS), Bengaluru',
    approval: 'National Medical Commission (NMC)',
    ranking: 'Collegedunia 2025: #583 (Medical, India); #61 in Karnataka',
    website: 'kanachurims.com',
    contact: '0824-2202282 | dean@kanachur.edu.in',
    teachingHospital: '975-bed hospital, ~1,950 OPD patients/day',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '2016' },
      { label: 'MBBS seats', value: '150 (127 general + 23 NRI)' },
      { label: 'Teaching hospital', value: '975 beds' },
      { label: 'Affiliation', value: 'RGUHS' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs (incl. 1-yr internship)',
        seats: '150 (127 general + 23 NRI)',
        eligibility: '10+2 PCB with 50% (40% reserved) + NEET UG',
        fees: 'Govt quota ~Rs 1.54 L/yr; Private ~Rs 12.0 L/yr; NRI ~Rs 32.1 L/yr; Collegedunia total (govt) ~Rs 7.72 L',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '14 PG specialities in total (MD + MS)',
        eligibility: 'MBBS + internship + NEET PG',
        fees: 'Private quota ~Rs 13.9 L/yr',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'General Surgery, Orthopaedics, Ophthalmology etc.',
        eligibility: 'MBBS + internship + NEET PG',
        fees: '1st yr ~Rs 7.14 L (Collegedunia)',
      },
    ],
    courseNotes: [
      'MD specialities include General Medicine and Radio-Diagnosis; MS covers General Surgery, Orthopaedics and Ophthalmology.',
      'Other programmes: B.Sc allied health (7 specialisations, ~Rs 7.2 L total), B.Sc Nursing, BPT, B.Pharm, BAMS (~Rs 15.9 L).',
    ],
    cutoffs: [
      { label: 'NEET UG 2024 (Karnataka, all categories)', value: 'Closing ranks ~66,908 - 2,38,392' },
      { label: 'NEET UG 2024 opening marks', value: '639 (Round 1) to 481 (Stray round)' },
    ],
    admissionSteps: [
      'MBBS: NEET UG -> Karnataka Examinations Authority (KEA) counselling for govt/private seats; MCC not applicable (state private college).',
      'NRI/management seats also allotted via KEA as per state rules.',
      'MD/MS: NEET PG -> KEA PG counselling (state); 50% All-India quota via MCC where applicable.',
      'Documents: NEET scorecard, 10th/12th marksheets, domicile (for govt quota), category certificate.',
    ],
    placements: [
      'No formal campus placement for MBBS; graduates move to PG entrance, junior residency or hospital jobs.',
      '1-year compulsory rotating internship at the attached 975-bed hospital (stipend as per Karnataka norms).',
    ],
    campusLife: [
      "Separate boys' and girls' hostels - MBBS hostel ~Rs 1.65 L/yr; PG hostel ~Rs 2.0 L/yr",
      'AC classrooms, auditorium, central library, Wi-Fi, gym and sports complex',
      'Coastal Mangalore setting; group campus with nursing, pharmacy and AYUSH colleges',
    ],
  },

  'kempegowda-institute-of-medical-sciences': {
    overview:
      "One of Bengaluru's older private medical colleges, run by the Rajya Vokkaligara Sangha, with its own KIMS teaching hospital in south Bengaluru. Known for large patient inflow and a strong alumni base in Karnataka.",
    established: '1980',
    type: 'Private (run by Rajya Vokkaligara Sangha)',
    affiliation: 'RGUHS, Bengaluru',
    approval: 'NMC; listed with WHO; GMC (UK) recognised',
    ranking: 'Collegedunia 2025: #485 (Medical)',
    website: 'kimsbangalore.edu.in',
    contact: '080-26715790',
    teachingHospital: 'KIMS Hospital & Research Centre (attached)',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '1980' },
      { label: 'MBBS seats', value: '250' },
      { label: 'Ranking', value: 'Collegedunia #485 Medical' },
      { label: 'Approval', value: 'NMC / WHO / GMC (UK)' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '250',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: 'Govt: ~Rs 2.11 L 1st yr (~Rs 6.9 L total); Private: ~Rs 12.6 L/yr (~Rs 60 L total); NRI/Mgmt: ~Rs 42.7 L/yr',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '17+ specialities (Anaesthesiology, Medicine, Paediatrics, etc.)',
        eligibility: 'MBBS (55%) + 1-yr internship + NEET PG',
        fees: 'Govt ~Rs 0.96-7.68 L; Private ~Rs 1.72-13.72 L (per yr)',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'General Surgery, Ortho, OBG, ENT, Ophthalmology',
        eligibility: 'MBBS + internship + NEET PG',
        fees: 'Similar to MD fee bands',
      },
      {
        name: 'Diploma / Paramedical',
        duration: '2.5-3.5 yrs',
        seats: 'Various',
        eligibility: 'As per course',
        fees: '-',
      },
    ],
    courseNotes: [
      'MBBS seat split: ~40% Government, ~40% Private, ~15% NRI, ~5% others.',
      'Hostel fee extra (~Rs 36,500/yr as per Collegedunia).',
    ],
    cutoffs: [
      { label: 'NEET UG 2024 KEA - General Merit (GM)', value: '15,053 - 19,074 (closing rank)' },
      { label: 'Category 2A', value: '46,544 - 50,231' },
      { label: 'Category 2B', value: '29,134' },
      { label: 'Category 3A', value: '19,094 - 19,243' },
      { label: 'Category 1 (OBC)', value: '47,447' },
      { label: 'SC', value: '1,16,580 - 1,34,835' },
    ],
    admissionSteps: [
      'MBBS: NEET UG -> KEA (Karnataka) counselling for govt, private & NRI seats.',
      'MD/MS: NEET PG -> Karnataka PG counselling (KEA) / MCC for AIQ seats.',
      'Multiple rounds: Round 1, Round 2, Mop-up and Stray vacancy.',
    ],
    placements: [
      'Clinical exposure at KIMS Hospital & Research Centre (attached).',
      'No separate placement report; interns receive stipend as per hospital/state norms; rural service bond applies to govt-quota students.',
    ],
    campusLife: [
      "Separate boys' and girls' hostels (~200 capacity each), 2-3 sharing, veg & non-veg mess, 24x7 security",
      'Gym, indoor games, new sports complex (basketball, volleyball, synthetic tennis courts), swimming pool',
      'Bus fleet, canteen, bank on campus',
    ],
  },

  'bgs-global-institute-of-medical-sciences': {
    overview:
      'Part of the BGS Health & Education City on Mysore Road, Bengaluru. Students train alongside the BGS Gleneagles Global multi-speciality hospital, giving good tertiary-care exposure.',
    established: '2013',
    type: 'Private (Sri Adichunchanagiri Shikshana Trust)',
    affiliation: 'RGUHS, Bengaluru',
    approval: 'NMC',
    ranking: '',
    website: 'bgsgims.edu.in',
    contact: '',
    teachingHospital: 'BGS Gleneagles Global Hospital; 680 teaching beds (college page lists 300 in medical college block)',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '2013' },
      { label: 'MBBS seats', value: '150 (127 general + 23 NRI)' },
      { label: 'Teaching hospital', value: '680 beds / BGS Gleneagles' },
      { label: 'Faculty', value: '200+ faculty, 21 departments' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150 (127 general + 23 NRI)',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: 'Govt ~Rs 1.54 L/yr; Private ~Rs 12.0 L/yr; NRI ~Rs 42.9 L/yr',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '~15 specialities (Anaesthesia, Medicine, Microbiology ...)',
        eligibility: 'MBBS + internship + NEET PG',
        fees: '~Rs 1.88 L - 13.9 L/yr (private quota)',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'General Surgery, OBG, Ophthalmology, Orthopaedics, ENT',
        eligibility: 'MBBS + internship + NEET PG',
        fees: 'Same band as MD',
      },
    ],
    courseNotes: [
      'Total MD/MS: ~18 specialities.',
      'Hostel extra: MBBS ~Rs 2.10 L/yr; PG ~Rs 2.35 L/yr.',
    ],
    cutoffs: [
      { label: 'KEA NEET UG 2024 - Round 1 marks', value: '650' },
      { label: 'Round 2 marks', value: '646' },
      { label: 'Mop-up marks', value: '624' },
      { label: 'KEA Round 1 (GM) closing rank (latest listed)', value: '37,576' },
    ],
    admissionSteps: [
      'NEET UG -> KEA counselling (govt/private/NRI seats).',
      'NEET PG -> KEA PG / MCC counselling.',
      'Eligibility for MBBS: 10+2 PCB with 50% (40% SC/ST/OBC) and NEET qualification.',
    ],
    placements: [
      '1-year internship; stipend ~Rs 5,000/month (Collegedunia).',
      'Post-internship junior residency available (~Rs 50,000/month reported).',
    ],
    campusLife: [
      "Separate boys' and girls' hostels",
      'Library with 400+ seats; lecture theatres of 250+ capacity',
      'Located inside BGS Health & Education City with sports and cultural facilities',
    ],
  },

  'sapthagiri-institute-of-medical-sciences': {
    overview:
      'Private medical college in north Bengaluru with a large attached multi-speciality hospital. Offers MBBS, MD/MS and allied health programmes.',
    established: '2011',
    type: 'Private (now under Sapthagiri NPS University)',
    affiliation: 'RGUHS (historically); Sapthagiri NPS University',
    approval: 'NMC',
    ranking: 'NAAC A+ (institution level)',
    website: 'simsrc.edu.in',
    contact: '+91-80-22188700',
    teachingHospital: '1,070 - 1,500-bed multi-speciality hospital',
    campusSize: '15 acres',
    highlights: [
      { label: 'Established', value: '2011' },
      { label: 'Campus', value: '15 acres' },
      { label: 'Teaching hospital', value: '1,070–1,500 beds' },
      { label: 'NAAC', value: 'A+' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150',
        eligibility: '10+2 PCB 50% (40% reserved) + NEET UG',
        fees: '1st yr ~Rs 1.83 L (govt quota); total ~Rs 9.16 L (govt quota). Private/NRI higher as per KEA matrix',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '14+ specialities (incl. Dermatology)',
        eligibility: 'MBBS + NEET PG',
        fees: '1st yr ~Rs 1.28 L - 7.39 L',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'General Surgery, OBG, Ortho, ENT, Ophthalmology',
        eligibility: 'MBBS + NEET PG',
        fees: '1st yr ~Rs 7.39 L',
      },
      {
        name: 'B.Sc / B.Sc Nursing / BPT',
        duration: '3-4 yrs',
        seats: '-',
        eligibility: '10+2',
        fees: '~Rs 55,000 1st yr',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'NEET UG 2024 (Karnataka quota) - General', value: '79,092 (closing rank)' },
      { label: 'OBC-2AG', value: '89,522' },
      { label: 'SC-3AG', value: '70,476' },
      { label: 'ST-3BG', value: '71,321' },
    ],
    admissionSteps: [
      'MBBS via NEET UG + KEA counselling; MD/MS via NEET PG + KEA/MCC.',
      '2026 cycle: Round 3 reporting 27 Sep 2026; stray vacancy registration 28-30 Sep 2026 (per Collegedunia).',
    ],
    placements: ['Clinical exposure in the in-house teaching hospital; no published placement statistics.'],
    campusLife: [
      "Separate boys' & girls' hostels, double/triple sharing for UG, single rooms mostly for PG",
      'Veg & non-veg mess, CCTV, Wi-Fi, laundry',
      'Badminton, volleyball, gym; bus transport; food court',
    ],
  },

  'vydehi-institute-of-medical-sciences-research-centre': {
    overview:
      'One of the largest private medical campuses in Bengaluru (65 acres, 1,600 beds) in the Whitefield IT corridor. Offers UG, PG and super-speciality (DM/M.Ch) training.',
    established: '2000',
    type: 'Private',
    affiliation: 'RGUHS, Bengaluru',
    approval: 'NMC',
    ranking: 'NIRF-related listing #459 (as reported); Collegedunia',
    website: 'vims.ac.in',
    contact: '',
    teachingHospital: '1,600-bed multi-speciality Vydehi Hospital',
    campusSize: '65 acres',
    highlights: [
      { label: 'Established', value: '2000' },
      { label: 'Campus', value: '65 acres' },
      { label: 'Teaching hospital', value: '1,600 beds' },
      { label: 'MBBS seats', value: '250' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '250',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: 'Govt quota low; Private/NRI high. Collegedunia NRI-level total ~Rs 1.81 Cr',
      },
      {
        name: 'MD/MS',
        duration: '3 yrs',
        seats: 'All major clinical & non-clinical',
        eligibility: 'MBBS + NEET PG',
        fees: '1st yr ~Rs 5.63 - 41.64 L',
      },
      {
        name: 'DM / M.Ch',
        duration: '3 yrs',
        seats: 'Cardiology, Oncology, Urology etc.',
        eligibility: 'MD/MS + NEET SS',
        fees: 'DM ~Rs 15 L; M.Ch ~Rs 6 L 1st yr',
      },
      {
        name: 'B.Sc allied / Nursing',
        duration: '3-4 yrs',
        seats: '-',
        eligibility: '10+2',
        fees: '~Rs 7-13 L total',
      },
    ],
    courseNotes: ['BDS listed as discontinued for current admission.'],
    cutoffs: [
      { label: 'Karnataka NEET UG 2025 - MBBS (GM)', value: '16,640 - 23,885' },
      { label: 'Karnataka NEET PG 2025 - MD General Medicine', value: '6,897 - 14,320' },
      { label: 'MS Orthopaedics', value: '27,625 - 60,996' },
      { label: 'NEET SS 2024 - DM Cardiology', value: '3,302' },
    ],
    admissionSteps: [
      'MBBS: NEET UG + KEA counselling.',
      'MD/MS: NEET PG + KEA/MCC.',
      'DM/M.Ch: NEET SS + MCC super-speciality counselling.',
    ],
    placements: [
      '1-year internship; stipend ~Rs 10,000/month.',
      'Graduates commonly work at Vydehi Hospital, Apollo, Manipal, Fortis, Aster hospitals (Collegedunia).',
    ],
    campusLife: [
      "Hostels: non-AC & AC, 2-3 sharing/single; Wi-Fi, study space; secure girls' hostels",
      'VASA simulation lab, large library',
      'Clubs: AMSA, Mediculture; annual cultural fest & medical conferences',
      'Scholarships: tuition waiver for meritorious PG (pre/para-clinical), Vidyasiri, SC/ST schemes',
    ],
  },

  'smt-kashibai-navale-medical-college-and-general-hospital': {
    overview:
      'Private medical college of the Sinhgad group with its own general hospital on the Mumbai-Pune bypass. Offers MBBS, 21 MD/MS disciplines and PG diplomas.',
    established: '2007',
    type: 'Private (Sinhgad Technical Education Society)',
    affiliation: 'Maharashtra University of Health Sciences (MUHS), Nashik',
    approval: 'NMC / MoHFW',
    ranking: 'Collegedunia: ~#340 India, #5 in Pune; NAAC Accredited (score 3.7 reported)',
    website: 'sknmcgh.org',
    contact: '',
    teachingHospital: '776 beds; ~1,085 OPD patients/day',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '2007' },
      { label: 'MBBS seats', value: '150 (15% AIQ / 85% state)' },
      { label: 'Teaching hospital', value: '776 beds' },
      { label: 'PG specialities', value: '21 disciplines' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150 (15% AIQ / 85% state; ~23 NRI)',
        eligibility: '12th with PCB+English, 50% + NEET UG',
        fees: '2025-26 per year: State/General ~Rs 12.35 L; Institutional/Management ~Rs 37.0 L; NRI ~Rs 61.7 L',
      },
      {
        name: 'MD/MS',
        duration: '3 yrs',
        seats: '100 seats, 21 specialities',
        eligibility: 'MBBS + internship + NEET PG',
        fees: 'Total ~Rs 12.9 L (Collegedunia listing)',
      },
      {
        name: 'PG Diploma',
        duration: '2-3 yrs',
        seats: '3 seats (Community Medicine, Pathology)',
        eligibility: 'MBBS',
        fees: '-',
      },
    ],
    courseNotes: [
      'Specialities include Anatomy, Physiology, Biochemistry, Pharmacology, Pathology, Microbiology, Community Medicine, Dermatology, General Medicine, Psychiatry, Paediatrics, Radio-diagnosis, Anaesthesiology, General Surgery, Orthopaedics, OBG, Ophthalmology, ENT etc.',
      'Maharashtra private-college fees are fixed each year by the Fee Regulating Authority (FRA).',
    ],
    cutoffs: [
      { label: 'NEET UG 2024 cutoff marks (mixed quotas)', value: 'R1 434 | R2 324 | R3 500 | Stray 222' },
      { label: 'State quota', value: 'Maharashtra CET Cell CAP rounds - refer to annual allotment lists' },
      { label: 'AIQ', value: '15% seats via MCC' },
    ],
    admissionSteps: [
      'NEET UG -> MCC (15% AIQ) and Maharashtra State CET Cell (85% state quota, institutional & NRI).',
      'MD/MS: NEET PG -> MCC (50%) + Maharashtra PG counselling (50%).',
    ],
    placements: ['No placement data published; graduates go for PG/residency.'],
    campusLife: [
      'MBBS hostel ~Rs 76,000/yr',
      'Library: ~16,900 books, e-library',
      '4 lecture halls (180 seats), 1,000-seat auditorium',
      'Separate UG & PG hostels; Sinhgad campus facilities',
    ],
  },

  'dr-n-y-tasgaonkar-institute-of-medical-sciences': {
    overview:
      'A new private medical college near Mumbai (Karjat) run by the Tasgaonkar group. MBBS intake grew from 100 to 150 and PG courses have started recently.',
    established: '2021',
    type: 'Private',
    affiliation: 'MUHS, Nashik',
    approval: 'NMC',
    ranking: '',
    website: 'nytims.in',
    contact: '',
    teachingHospital: '~400 beds',
    campusSize: '26 acres',
    highlights: [
      { label: 'Established', value: '2021' },
      { label: 'Campus', value: '26 acres' },
      { label: 'MBBS seats', value: '150 (earlier 100)' },
      { label: 'Teaching hospital', value: '~400 beds' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150 (earlier 100)',
        eligibility: '10+2 PCB + NEET UG',
        fees: 'Tuition ~Rs 5.65 L + dev. ~Rs 0.57 L/yr (state); total cost ~Rs 10-12 L/yr incl. others; Careers360 total ~Rs 45.1 L',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: 'Radio-diagnosis, General Medicine (4 each)',
        eligibility: 'MBBS + NEET PG',
        fees: 'As per FRA',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'ENT, Ophthalmology, General Surgery (4 each)',
        eligibility: 'MBBS + NEET PG',
        fees: 'As per FRA',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'NEET UG 2025 Maharashtra - General', value: 'R1 73,915 | R2 81,028 | R3 82,321' },
      { label: 'OBC', value: 'R1 75,923 | R2 79,302 | R3 82,321' },
      { label: 'SC', value: 'R1 1,61,897 | R3 1,72,842' },
      { label: 'ST', value: '3,65,586' },
    ],
    admissionSteps: [
      'NEET UG -> Maharashtra State CET Cell counselling (state/institutional/NRI) + MCC for 15% AIQ.',
      'MD/MS via NEET PG counselling.',
    ],
    placements: ['New college - no placement data; 1-year internship at attached hospital.'],
    campusLife: [
      "Boys' & girls' hostels, mess, 24-hr security",
      'Library, gym, labs, sports, transport from Karjat/Bhivpuri station',
    ],
  },

  'vedanta-institute-of-medical-sciences': {
    overview:
      'Private medical college with an attached multi-speciality teaching hospital on the Mumbai-Ahmedabad highway belt in Palghar district.',
    established: '2017',
    type: 'Private',
    affiliation: 'MUHS, Nashik',
    approval: 'NMC',
    ranking: '',
    website: 'vedantaa.institute',
    contact: '',
    teachingHospital: 'Attached multi-speciality teaching hospital',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '2017' },
      { label: 'MBBS seats', value: '150' },
      { label: 'Location', value: 'Dahanu, Palghar' },
      { label: 'Approval', value: 'NMC' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150',
        eligibility: '12th PCB+English 50% (40% reserved), age 17+ + NEET UG',
        fees: '~Rs 14.15 L tuition + Rs 1.42 L development per year (state quota)',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '9 specialities',
        eligibility: 'MBBS + NEET PG',
        fees: 'e.g. MD Anatomy ~Rs 8 L; MD Pathology Rs 19.3 L (state) - Rs 96.6 L (NRI)',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: '5 specialities',
        eligibility: 'MBBS + NEET PG',
        fees: 'MS General Surgery Rs 19.3 L (state) - Rs 96.6 L (NRI)',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'NEET UG 2025 state quota - General', value: 'R1 95,521 -> R3 1,33,806' },
      { label: 'OBC', value: 'R1 94,569 -> R3 1,29,553' },
      { label: 'SC', value: '1,87,092 - 2,07,356' },
      { label: 'ST', value: '4,03,074 - 4,28,995' },
    ],
    admissionSteps: [
      'NEET UG -> Maharashtra CET Cell (85%) + MCC (15% AIQ).',
      'MD/MS: NEET PG -> MCC / state PG counselling.',
    ],
    placements: ['No placement data; 1-year internship at attached hospital.'],
    campusLife: ["Separate boys' & girls' hostels", 'Library, modern labs, 24x7 security'],
  },

  'd-y-patil-medical-college-hospital-and-research-centre': {
    overview:
      'Flagship medical college of Dr. D. Y. Patil Vidyapeeth, Pune with a large tertiary-care hospital. Deemed-university status means admissions run through MCC deemed counselling.',
    established: '1996',
    type: 'Private - constituent of Dr. D. Y. Patil Vidyapeeth (Deemed University)',
    affiliation: 'Dr. D. Y. Patil Vidyapeeth (Deemed University)',
    approval: 'NMC; NAAC A++ (CGPA 3.64)',
    ranking: 'NIRF Medical top-50 band; IIRF Medical #41',
    website: 'medical.dpu.edu.in',
    contact: '020-27805100',
    teachingHospital: 'DY Patil Hospital (Pimpri)',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '1996' },
      { label: 'MBBS seats', value: '250' },
      { label: 'NAAC', value: 'A++ (CGPA 3.64)' },
      { label: 'Ranking', value: 'NIRF Medical top-50; IIRF #41' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '250',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: '1st yr ~Rs 29.5 L; total ~Rs 1.33 Cr',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '15+ (Medicine, Radiology, Paediatrics, Dermatology, Psychiatry...)',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 9.5 L - 67.5 L/yr (e.g. MD Paediatrics ~Rs 47.5 L/yr, 18 seats)',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'OBG, Ortho, Surgery, ENT, Ophthalmology',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 37.5 - 57.5 L/yr',
      },
      {
        name: 'M.Ch / DM',
        duration: '3 yrs',
        seats: 'Urology & 5+ others',
        eligibility: 'MS/MD + NEET SS',
        fees: '~Rs 1.5 L - 50.5 L',
      },
    ],
    courseNotes: ['Also M.Sc, fellowships and certificate courses.'],
    cutoffs: [
      { label: 'NEET UG 2024 MCC deemed - Management', value: 'R1 5,68,091 | R2 5,32,578 | R3 5,38,205 (AIR)' },
      { label: 'NRI', value: 'R1 11,54,944 | R2 13,68,675' },
    ],
    admissionSteps: [
      '100% seats (management/NRI) through MCC Deemed University counselling on NEET UG AIR.',
      'MD/MS through MCC deemed PG counselling on NEET PG.',
    ],
    placements: [
      'PG placements 2023: 180 placed, median ~Rs 25.45 LPA; 2022: 161 placed, median ~Rs 22.10 LPA (NIRF data via Collegedunia).',
      'MBBS interns train at DY Patil Hospital (Pimpri).',
    ],
    campusLife: [
      'Well-furnished hostels, mess, coffee shop',
      'Central library 35,000+ books; Wi-Fi campus',
      'Central AC auditorium; sports & cultural events of DPU',
    ],
  },

  'heritage-institute-of-medical-sciences': {
    overview:
      'Private medical college on the GT Road bypass near Varanasi with its own hospital, offering MBBS and 11 PG disciplines.',
    established: '2015',
    type: 'Private',
    affiliation: 'Atal Bihari Vajpayee Medical University, Lucknow (earlier MGKVP)',
    approval: 'NMC',
    ranking: 'Outlook 2024 (Medical, private): #24',
    website: 'heritageims.com',
    contact: '0542-7111071',
    teachingHospital: 'Own hospital attached',
    campusSize: '',
    highlights: [
      { label: 'Established', value: '2015' },
      { label: 'MBBS seats', value: '200' },
      { label: 'PG seats', value: '46 across 11 disciplines' },
      { label: 'Ranking', value: 'Outlook 2024 private #24' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '200',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: '1st yr ~Rs 18.6 L; total ~Rs 75 L',
      },
      {
        name: 'MD/MS',
        duration: '3 yrs',
        seats: '46 seats across Radio-diagnosis, Medicine, OBG, Paediatrics, Ortho, Ophthalmology, Surgery, Anaesthesia, Pathology, Respiratory Med., Pharmacology',
        eligibility: 'MBBS + NEET PG',
        fees: '1st yr ~Rs 16.7 - 29.5 L; total ~Rs 39 - 77 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'UP NEET UG 2024 - General (state rank)', value: 'R1 2,56,128 | R2 1,75,090 | R3 1,15,841' },
      { label: 'UP NEET PG 2024', value: 'Closing ranks ~1,026 - 8,045 (state merit)' },
    ],
    admissionSteps: [
      'NEET UG -> UP NEET counselling (DGME Lucknow).',
      'NEET PG -> UP NEET PG counselling.',
    ],
    placements: ['No formal placements; 1-year internship with stipend ~Rs 5,000/month (as reported).'],
    campusLife: [
      'Separate hostels with mess',
      '28,000 sq ft library, computer lab',
      'Playground, gymnasium, AV-enabled demo rooms',
    ],
  },

  'santosh-medical-college': {
    overview:
      'Delhi-NCR deemed-university medical college run by the Maharaji Educational Trust. Admissions are through MCC deemed-university counselling.',
    established: '1995',
    type: 'Constituent of Santosh Deemed to be University (deemed status 2007)',
    affiliation: 'Santosh Deemed to be University',
    approval: 'NMC, UGC; NAAC A+',
    ranking: '',
    website: 'santosh.ac.in',
    contact: '',
    teachingHospital: '900+ beds',
    campusSize: '26.6 acres',
    highlights: [
      { label: 'Established', value: '1995' },
      { label: 'Campus', value: '26.6 acres' },
      { label: 'Hospital', value: '900+ beds' },
      { label: 'MBBS seats', value: '150' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150',
        eligibility: '12th PCB 50% (40% reserved), age 17+ + NEET UG',
        fees: '~Rs 24 L per year (total ~Rs 1.08 Cr); NRI ~US$30,650/yr',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '17 specialities',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 0.75 L - 76 L per yr depending on branch',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: '6 specialities (Surgery, OBG, Ortho, ENT, Ophthalmology...)',
        eligibility: 'MBBS + NEET PG',
        fees: 'As above',
      },
    ],
    courseNotes: ['PG stipend ~Rs 56,010/month (as reported).'],
    cutoffs: [
      { label: 'MCC deemed 2025 - General (AIR)', value: 'R1 4,99,941 | R2 5,23,387 | R3 5,88,923 | R4 6,32,652' },
      { label: 'NRI', value: 'R2 10,52,586 | R3 8,78,397' },
    ],
    admissionSteps: ['100% seats through MCC Deemed University counselling on NEET UG / NEET PG AIR.'],
    placements: ['Hospital with 200+ specialists provides clinical exposure; no formal placement data.'],
    campusLife: [
      'MBBS hostel (AC): single ~Rs 4.5 L, double ~Rs 4.0 L, 4-seater ~Rs 3.0 L per yr',
      'PG hostel: ~Rs 1.5 - 3.0 L per yr',
      'NCR location with metro connectivity',
    ],
  },

  'venkateshwara-institute-of-medical-sciences': {
    overview:
      "Private medical college on NH-24 (Delhi-Moradabad) with a 1,400+ bed hospital and one of UP's larger MBBS intakes.",
    established: '2014',
    type: 'Private (trust)',
    affiliation: 'Shri Venkateshwara University, Gajraula',
    approval: 'NMC',
    ranking: '',
    website: 'vimshospital.edu.in',
    contact: '',
    teachingHospital: 'Venkateshwara Hospital, 1,400+ beds',
    campusSize: '26 acres',
    highlights: [
      { label: 'Established', value: '2014' },
      { label: 'Campus', value: '26 acres' },
      { label: 'MBBS seats', value: '250' },
      { label: 'Hospital', value: '1,400+ beds' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '250',
        eligibility: '12th PCB+English 50% (40% reserved) + NEET UG',
        fees: '~Rs 11.1 L per year',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: 'Gen. Medicine 14, Paediatrics 10, Anaesthesia 8, Pathology 8, Dermatology 7, Psychiatry 7, Radio-diag 6',
        eligibility: 'MBBS 50% + internship + NEET PG',
        fees: 'Clinical ~Rs 21.6 L/yr; Pathology ~Rs 12.0 L/yr',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'Gen. Surgery 10, OBG 10, Ortho 7, ENT 5, Ophthalmology 4',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 21.6 L/yr',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'UP NEET UG 2025 - General (state rank)', value: 'R1 2,70,848 | last round 3,24,506' },
      { label: 'UP NEET UG 2024 - General', value: 'R1 4,20,195 | last 79,264' },
    ],
    admissionSteps: [
      'NEET UG -> UP state counselling (DGME, Lucknow).',
      'NEET PG -> UP PG counselling.',
    ],
    placements: ['No formal placement; internship at 1,400-bed hospital.'],
    campusLife: [
      'UG hostel: non-AC ~Rs 1.73 L, AC ~Rs 2.02 L per yr',
      'PG hostel: ~Rs 2.0 - 3.5 L per yr',
      'CCTV, mess, Wi-Fi, laundry',
    ],
  },

  'icare-institute-of-medical-sciences-and-research': {
    overview:
      'Private medical college in the port town of Haldia, trained through the attached Dr. B. C. Roy Hospital.',
    established: '2011',
    type: 'Private (ICARE trust)',
    affiliation: 'West Bengal University of Health Sciences (WBUHS)',
    approval: 'NMC',
    ranking: 'Collegedunia: #350 India, #28 West Bengal',
    website: 'icaremedicalcollege.in',
    contact: '(03224) 269261',
    teachingHospital: 'Dr. B. C. Roy Hospital, 500+ beds',
    campusSize: '34+ acres',
    highlights: [
      { label: 'Established', value: '2011' },
      { label: 'Campus', value: '34+ acres' },
      { label: 'MBBS seats', value: '200 (edufever) / 150 (older listings)' },
      { label: 'Hospital', value: '500+ beds' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '200 (edufever) / 150 (older listings)',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: 'State quota ~Rs 9 L/yr; Management ~Rs 23 L/yr; Collegedunia total ~Rs 26 L (state)',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '12 specialities (Anaesthesiology 7 seats, Radio-diag 4, Dermatology 4 ...)',
        eligibility: 'MBBS + NEET PG',
        fees: 'Total ~Rs 12.8 L - 43.1 L (state)',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'ENT, OBG',
        eligibility: 'MBBS + NEET PG',
        fees: 'Total ~Rs 43.1 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'WB NEET UG 2025 - General (AIR)', value: 'R1 4,57,844 | R2 3,92,410 | R3 4,80,227 (edufever)' },
      { label: 'WB Round 2 (Collegedunia listing)', value: '59,783 (state quota)' },
    ],
    admissionSteps: [
      'NEET UG -> West Bengal Medical Counselling Committee (WBMCC) for state & management quota; 15% AIQ not applicable to private seats.',
      'NEET PG -> WBMCC PG counselling.',
    ],
    placements: ['1-year internship at Dr. B. C. Roy Hospital; no placement data published.'],
    campusLife: [
      'Hostels for boys & girls',
      'Smart classrooms, labs, library',
      'Collegedunia student rating ~4.1/5',
    ],
  },

  'k-p-c-medical-college-and-hospital': {
    overview:
      "Kolkata's well-known private medical college in Jadavpur. Strong state-quota demand makes its cutoffs among the tightest of WB private colleges.",
    established: '2006',
    type: 'Private',
    affiliation: 'WBUHS',
    approval: 'NMC; INC for nursing',
    ranking: '',
    website: 'kpcmedicalcollege.in',
    contact: '(033) 6621-1713',
    teachingHospital: 'Attached KPC hospital',
    campusSize: '49 acres; 1.2 million sq ft built-up',
    highlights: [
      { label: 'Established', value: '2006' },
      { label: 'Campus', value: '49 acres' },
      { label: 'MBBS seats', value: '150' },
      { label: 'Location', value: 'Jadavpur, Kolkata' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: 'State ~Rs 18 L total; Management ~Rs 72 L; NRI ~Rs 1.5 Cr',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '49 seats, 12 specialities',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 26.25 L',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: '8 seats (Orthopaedics, ENT)',
        eligibility: 'MBBS + NEET PG',
        fees: 'As per WB fee',
      },
      {
        name: 'B.Sc Nursing / BPT / BHA / BMLT',
        duration: '3-4 yrs',
        seats: '80 / 25 / 40 / -',
        eligibility: '10+2',
        fees: 'Nursing ~Rs 1.95 L 1st yr; BPT ~Rs 2.8 L',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'WB NEET UG 2024 - General', value: 'R1 7,437 | R2 12,461 | R3 13,631 | R4 15,973 (state rank)' },
      { label: 'OBC', value: 'R1 8,061 -> R4 17,873' },
      { label: 'EWS', value: 'R1 9,196 -> R3 15,673' },
      { label: 'SC', value: 'R1 48,498 -> R3 99,260' },
      { label: 'ST', value: 'R1 99,342 -> R3 1,24,137' },
      { label: 'NEET PG 2024 - General (AIR)', value: 'R1 99,813 -> R4 1,79,632' },
    ],
    admissionSteps: [
      'NEET UG -> WBMCC state counselling (state/management/NRI).',
      'NEET PG -> WBMCC PG counselling.',
    ],
    placements: [
      'Internship stipend ~Rs 15,000-20,000/month (Collegedunia).',
      'Paths: PG, junior residency, emergency medicine, rural service.',
    ],
    campusLife: [
      'Separate hostels; sports complex (badminton etc.)',
      'Modern labs, attached KPC hospital',
      'City location in south Kolkata',
    ],
  },

  'sanaka-medical-college': {
    overview:
      "Popularly called 'Sanaka Medical College', it is run by the Sanaka Educational Trust with a large multi-speciality and cancer hospital (MRI, 64-slice CT, PET-CT).",
    established: '2019',
    type: 'Private (Sanaka Educational Trust)',
    affiliation: 'WBUHS, Kolkata',
    approval: 'NMC',
    ranking: '',
    website: 'srims.setgoi.ac.in',
    contact: '',
    teachingHospital: 'Sanaka Hospitals, 1,100+ beds incl. cancer hospital',
    campusSize: '51+ acres',
    highlights: [
      { label: 'Established', value: '2019' },
      { label: 'Campus', value: '51+ acres' },
      { label: 'MBBS seats', value: '250' },
      { label: 'Hospital', value: '1,100+ beds' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '250',
        eligibility: '12th PCB+English 50% (40% reserved) + NEET UG',
        fees: 'State ~Rs 2.74 L per semester; Management ~Rs 10.94 L per semester',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: 'Medicine 5, Anaesthesia 4, Paediatrics 3, Radio-diag 3',
        eligibility: 'MBBS 50% + internship + NEET PG',
        fees: 'State ~Rs 24.7 L total; Management ~Rs 98.5 L total',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'Surgery 5, Ortho 3, OBG 4',
        eligibility: 'MBBS + NEET PG',
        fees: 'As MD',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'WB NEET UG 2025 - state quota', value: 'R1 60,943 | R2 63,123 | R3 70,813 | final 74,558' },
      {
        label: 'NEET PG 2025 closing',
        value: 'MD Medicine 46,881; Anaesthesia 24,804; Paediatrics 78,312; MS Surgery 87,967; Ortho 89,151',
      },
    ],
    admissionSteps: ['NEET UG / NEET PG -> West Bengal Medical Counselling Committee (WBMCC).'],
    placements: ['No placement data; internship at Sanaka Hospitals.'],
    campusLife: [
      'Separate hostels - twin/triple/quad sharing, 24x7 power & water, CCTV',
      'AC lecture theatres (180-300), skill/simulation labs, e-library',
      '12+ major OTs; NICU/PICU/SICU/ICCU',
    ],
  },

  'shri-shankaracharya-institute-of-medical-sciences': {
    overview:
      'Private medical college of the Shri Shankaracharya group in Bhilai, with a teaching hospital and MD/MS programmes.',
    established: '2013',
    type: 'Private (Shri Gangajali Education Society)',
    affiliation: 'Pt. Deendayal Upadhyay Memorial Health Sciences & AYUSH University, Raipur',
    approval: 'NMC',
    ranking: 'Collegedunia: #421 India, #9 Chhattisgarh',
    website: 'ssimsb.ac.in',
    contact: '0788 408 8866',
    teachingHospital: 'Teaching hospital 200+ beds (as reported)',
    campusSize: '~21 acres',
    highlights: [
      { label: 'Established', value: '2013' },
      { label: 'Campus', value: '~21 acres' },
      { label: 'MBBS seats', value: '150' },
      { label: 'Faculty', value: '250+ across 21 departments' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150',
        eligibility: '10+2 PCB 50% + NEET UG',
        fees: '2025-26: ~Rs 7.99 L per year (state/management); NRI ~US$35,000/yr; Collegedunia total ~Rs 67.8 L',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: '15 specialities (Anaesthesia, Anatomy, OBG ...)',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 36.3 - 60.5 L total',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'General Surgery, OBG, Orthopaedics',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 51.5 - 60.5 L total',
      },
      {
        name: 'Paramedical certificates',
        duration: '1 yr',
        seats: '35 (X-ray, OT, ECG/ICCU tech)',
        eligibility: '10+2',
        fees: '-',
      },
    ],
    courseNotes: [],
    cutoffs: [
      { label: 'NEET UG 2024-25 closing marks - General (UR)', value: '~508 - 512 (UR-Female ~525 - 530)' },
      { label: 'OBC', value: '~455 - 460' },
      { label: 'SC', value: '~315 - 320' },
      { label: 'ST', value: '~185 - 190' },
    ],
    admissionSteps: [
      'NEET UG -> Chhattisgarh DME counselling (state/management/NRI) + no AIQ for private.',
      'NEET PG -> CG PG counselling.',
    ],
    placements: ['Internship stipend ~Rs 8,000-13,000/month (as reported).'],
    campusLife: [
      "Boys' & girls' hostels, ~Rs 2 - 3 L per year (edufever: Rs 3.03 L)",
      'Teaching hospital 200+ beds (as reported)',
      'Library, auditorium, gym, canteen, playground',
    ],
  },

  'raipur-institute-of-medical-sciences-rims': {
    overview:
      'Private medical college on the outskirts of Raipur with a 650+ bed hospital (ICU, cath-lab, dialysis, CT/MRI).',
    established: '2012',
    type: 'Private',
    affiliation: 'Pt. Deendayal Upadhyay Memorial Health Sciences & AYUSH University, Raipur',
    approval: 'NMC',
    ranking: '',
    website: 'rimsindia.ac.in',
    contact: '',
    teachingHospital: '650-750+ beds',
    campusSize: '25 acres',
    highlights: [
      { label: 'Established', value: '2012' },
      { label: 'Campus', value: '25 acres' },
      { label: 'MBBS seats', value: '150' },
      { label: 'Hospital', value: '650-750+ beds' },
    ],
    courses: [
      {
        name: 'MBBS',
        duration: '5.5 yrs',
        seats: '150',
        eligibility: '12th PCB+English 50% (40% reserved) + NEET UG',
        fees: 'Tuition ~Rs 7.45 L + other charges = ~Rs 9.35 - 10.85 L per yr',
      },
      {
        name: 'MD',
        duration: '3 yrs',
        seats: 'Medicine 5, Paediatrics 6, Psychiatry 3, Pathology 5, Community Med 6 (+ Anaesthesia, Microbiology, Radiology, Pharmacology)',
        eligibility: 'MBBS + NEET PG',
        fees: 'Clinical ~Rs 9.3-9.8 L/yr; non-clinical ~Rs 7.5-7.9 L/yr',
      },
      {
        name: 'MS',
        duration: '3 yrs',
        seats: 'Ortho 4, Surgery 8, OBG 3, ENT 3, Ophthalmology',
        eligibility: 'MBBS + NEET PG',
        fees: '~Rs 9.3 - 9.8 L/yr',
      },
    ],
    courseNotes: [],
    cutoffs: [
      {
        label: 'CG NEET UG 2024 closing (AIR)',
        value: 'General 1,28,146 | EWS 2,14,681 | OBC 3,69,046 | SC 8,10,144 | ST 12,48,120',
      },
    ],
    admissionSteps: [
      'NEET UG -> Chhattisgarh DME state counselling.',
      'NEET PG -> CG PG counselling.',
    ],
    placements: ['Internship at attached hospital; no placement data.'],
    campusLife: [
      'Separate hostels with attached bathrooms',
      'Wi-Fi campus, dining facilities',
      'ICU/CCU/NICU, dialysis, cath lab, CT/MRI',
    ],
  },
};
